/*! JST runtime-only build v0.7.6 — generated by tools/build_global.mjs. Do not edit by hand. */
/*! © Brent Jacobs · https://github.com/br3nt/jst · MIT */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
function compileTemplateRenderingFunction() {
  throw new Error('JST runtime-only build: in-browser compilation of <script type="jst"> templates is unavailable. Precompile with tools/precompile.mjs and register via registerPrecompiledTemplate, or load the full build (jst.js / jst.global.js).');
}

/**
 * JST Framework Core
 *
 * Templates are declared as <script type="jst" name="tag-name" attributes="prop otherProp">
 * and registered as real custom elements. Data flows in through attributes
 * (JSON-parsed primitives) or properties (rich values: el.items = [...]).
 * Data flows out through bubbling CustomEvents (el.emit('name', detail)).
 *
 * Inside templates:
 *   $(expr)                 escaped interpolation
 *   $(trustedHTML(expr))    unescaped interpolation (opt-in trusted HTML)
 *   $(url(expr))            URL helper for href/src values
 *   $(slot())               project the component's original child nodes
 *   $(slot('name', 'fb'))   project nodes marked slot="name", with a fallback
 *   .prop="$(expr)"         assign expr as a JS property on the element
 *   onevent="body"          a plain FUNCTION BODY — the native inline-handler
 *                           contract (`event` in scope, `this` = the element) —
 *                           compiled in render scope, attached with
 *                           addEventListener. Dotted modifiers configure
 *                           registration only (.capture .passive .once .outside)
 *   onreveal="body"         synthetic event: fires when the element scrolls into
 *                           view (a real CustomEvent('reveal') is dispatched)
 *   combinators             statement combinators in scope in handler bodies:
 *                           oninput="if (changed(event)) debounce(event, 300, () => …)"
 *                           onkeydown="keys(event, { Enter: () => … })"
 *   jst-model="prop"        local form shorthand: read prop, update el[prop]
 *   once('key', setup)      run setup once per connection, after the DOM commits;
 *                           a returned function is registered as disconnect cleanup
 *   jst-key="$(id)"         preserve keyed node identity while morphing
 *   jst-preserve            freeze this node against morph: attributes and
 *                           whole subtree are left untouched (loaded iframe,
 *                           media playback, canvas, third-party widget)
 *
 * State lives in this module. The ES-module exports are the canonical API; a
 * reduced `window.JST` global mirrors them for non-module/streamed consumers.
 */
/**
 * The version of the loaded runtime. Sourced from package.json and kept in sync
 * by a drift test (runtime_tests.mjs) — a browser ES module can't read
 * package.json at runtime, so this constant is the single in-runtime source of
 * truth. Useful given the no-build "serve the file directly" model: a stale
 * v0.1 cache renders identically to v0.2, so `JST.version` is the one-liner that
 * tells you which runtime is actually live.
 */
export const version = '0.7.6'

const templates = new Map()
const config = {
  dev: false,
  autoRegister: true,
  autoRegisterRoot: null,
  resolveTemplate: null,
  // Opt-in: wire the on* attributes the platform does NOT implement (component
  // custom events, onreveal) in plain body HTML, by evaluating the attribute
  // string the way the browser evaluates its own inline handlers. Default off,
  // see the security note on wireInlineBodyHandlers. Deliberately not coupled
  // to `dev`: a flag that changes security semantics between dev and prod is a
  // footgun.
  unsafeInlineHandlers: false,
}

let templatesInitialized = false
let templateObserver = null
let versionAnnounced = false
const pendingTemplateResolutions = new Map()

/** In dev, log the live runtime version once so a stale cache is obvious. */
function announceVersion() {
  if (versionAnnounced || !config.dev) return;
  if (typeof console === 'undefined' || typeof console.info !== 'function') return;
  versionAnnounced = true;
  console.info(`JST ${version}`);
}

/** Values wrapped in RawHtml bypass interpolation escaping. */
class RawHtml {
  constructor(html) { this.html = html }
}

export function trustedHTML(value) {
  if (value instanceof RawHtml) return value
  return new RawHtml(value == null ? '' : String(value))
}

export function url(value) {
  const string = value == null ? '' : String(value).trim()
  const scheme = string.match(/^([a-z][a-z0-9+.-]*):/i)
  if (scheme && !['http', 'https', 'mailto', 'tel', 'ftp'].includes(scheme[1].toLowerCase())) {
    console.warn(`JST: blocked unsafe URL scheme in "${string}".`)
    return '#'
  }
  return string
}

export function configure(options = {}) {
  const shouldRewire = Object.prototype.hasOwnProperty.call(options, 'autoRegister')
    || Object.prototype.hasOwnProperty.call(options, 'autoRegisterRoot')
    || Object.prototype.hasOwnProperty.call(options, 'resolveTemplate');

  Object.assign(config, options);
  announceVersion();
  if (config.unsafeInlineHandlers) wireInlineBodyHandlers(document);

  if (shouldRewire && templateObserver) {
    templateObserver.disconnect();
    templateObserver = null;
  }

  observeNewTemplates();

  // Auto-init runs at module eval, before an importing module can call
  // configure() — so any resolveTemplate set here was null during the initial
  // scanForMissingTemplates, and components already in the server-rendered HTML
  // were skipped (resolveTemplateForName bails when the resolver isn't a
  // function). Re-scan now that the resolver exists. This is idempotent:
  // resolveTemplateForName ignores names already defined/registered and
  // coalesces in-flight fetches, so re-scanning costs nothing for resolved ones.
  if (templatesInitialized && typeof config.resolveTemplate === 'function') {
    scanForMissingTemplates(document.documentElement);
  }

  return config
}

function isCustomElementName(name) {
  return typeof name === 'string' && name.includes('-');
}

function templateSource(templateElement) {
  return templateElement.dataset?.jstSource || templateElement.ownerDocument?.baseURI || '';
}

function insertTemplateHtml(html, source) {
  const container = document.createElement('div');
  container.hidden = true;
  container.setAttribute('data-jst-resolved-from', source);
  container.innerHTML = html;
  container.querySelectorAll('script[type="jst"]').forEach(script => {
    script.dataset.jstSource = source;
  });

  (document.body || document.head || document.documentElement).appendChild(container);
  container.querySelectorAll('script[type="jst"]').forEach(registerCustomElementFromTemplate);
  return container;
}

async function resolveTemplateForName(name) {
  const resolver = config.resolveTemplate;
  if (typeof resolver !== 'function') return null;
  if (!isCustomElementName(name) || customElements.get(name) || templates.has(name)) return null;
  if (pendingTemplateResolutions.has(name)) return pendingTemplateResolutions.get(name);

  const resolution = Promise.resolve()
    .then(() => resolver(name))
    .then(async url => {
      if (!url) return null;
      const response = await fetch(url);
      if (!response.ok) throw new Error(`HTTP ${response.status} while fetching ${url}`);
      const html = await response.text();
      return insertTemplateHtml(html, String(url));
    })
    .catch(error => {
      console.error(`JST: Failed to resolve template for <${name}>:`, error);
      return null;
    })
    .finally(() => {
      pendingTemplateResolutions.delete(name);
    });

  pendingTemplateResolutions.set(name, resolution);
  return resolution;
}

function scanForMissingTemplates(root) {
  if (!root || typeof root.querySelectorAll !== 'function') return;

  const visit = element => {
    if (element.nodeType !== Node.ELEMENT_NODE) return;
    const name = element.tagName.toLowerCase();
    if (isCustomElementName(name) && !customElements.get(name)) resolveTemplateForName(name);
  };

  visit(root);
  root.querySelectorAll('*').forEach(visit);
}

export function escapeHtml(value) {
  if (value == null) return ''
  if (value instanceof RawHtml) return value.html
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function createSlotPlaceholder(name, fallback) {
  const nameAttribute = name ? ` name="${escapeHtml(name)}"` : ''
  const fallbackHtml = fallback == null ? '' : escapeHtml(fallback)
  return new RawHtml(`<jst-slot${nameAttribute} style="display: contents">${fallbackHtml}</jst-slot>`)
}

function canMorphDom(host) {
  return typeof document?.createElement === 'function' && !!host?.childNodes;
}

function isManagedCustomElement(node) {
  return node?.nodeType === Node.ELEMENT_NODE
    && typeof customElements?.get === 'function'
    && !!customElements.get(node.tagName.toLowerCase());
}

function isSlotElement(node) {
  return node?.nodeType === Node.ELEMENT_NODE && node.tagName === 'JST-SLOT';
}

function nodesAreCompatible(currentNode, nextNode) {
  if (!currentNode || !nextNode) return false;
  if (currentNode.nodeType !== nextNode.nodeType) return false;

  if (currentNode.nodeType === Node.ELEMENT_NODE) {
    return currentNode.tagName === nextNode.tagName;
  }

  return true;
}

function getNodeKey(node) {
  if (node?.nodeType !== Node.ELEMENT_NODE) return null;
  if (node.hasAttribute('data-jst-leaving')) return null;
  return node.getAttribute('jst-key');
}

function findKeyedChild(host, nextNode, startIndex) {
  const key = getNodeKey(nextNode);
  if (key == null) return null;

  for (let i = startIndex; i < host.childNodes.length; i++) {
    const candidate = host.childNodes[i];
    if (getNodeKey(candidate) === key && nodesAreCompatible(candidate, nextNode)) {
      return candidate;
    }
  }

  return null;
}

function transitionName(node) {
  return node?.nodeType === Node.ELEMENT_NODE ? node.getAttribute('jst-transition') : null;
}

function parseCssTimeList(value) {
  return String(value || '')
    .split(',')
    .map(part => part.trim())
    .filter(Boolean)
    .map(part => part.endsWith('ms') ? Number.parseFloat(part) : Number.parseFloat(part) * 1000)
    .filter(Number.isFinite);
}

function transitionTimeoutMs(element) {
  if (typeof getComputedStyle !== 'function') return 0;
  const style = getComputedStyle(element);
  const transitionDurations = parseCssTimeList(style.transitionDuration);
  const transitionDelays = parseCssTimeList(style.transitionDelay);
  const animationDurations = parseCssTimeList(style.animationDuration);
  const animationDelays = parseCssTimeList(style.animationDelay);
  const maxFor = (durations, delays) => durations.reduce((max, duration, index) => {
    const delay = delays[index] ?? delays[0] ?? 0;
    return Math.max(max, duration + delay);
  }, 0);

  return Math.max(
    maxFor(transitionDurations, transitionDelays),
    maxFor(animationDurations, animationDelays),
  );
}

function nextFrame(callback) {
  if (typeof requestAnimationFrame === 'function') {
    requestAnimationFrame(() => requestAnimationFrame(callback));
    return;
  }
  setTimeout(callback, 0);
}

function afterTransition(element, callback) {
  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    element.removeEventListener('transitionend', finish);
    element.removeEventListener('animationend', finish);
    callback();
  };
  const timeout = transitionTimeoutMs(element);

  element.addEventListener('transitionend', finish);
  element.addEventListener('animationend', finish);
  setTimeout(finish, timeout > 0 ? timeout + 50 : 0);
}

function removeTransitionClasses(element, name, phase) {
  element.classList.remove(
    `${name}-${phase}-from`,
    `${name}-${phase}-active`,
    `${name}-${phase}-to`,
  );
}

function runEnterTransition(node) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) return;

  node.classList.add(`${name}-enter-from`, `${name}-enter-active`);
  nextFrame(() => {
    node.classList.remove(`${name}-enter-from`);
    node.classList.add(`${name}-enter-to`);
    afterTransition(node, () => removeTransitionClasses(node, name, 'enter'));
  });
}

function runLeaveTransition(node, remove) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) {
    remove();
    return;
  }

  node.setAttribute('data-jst-leaving', '');
  node.removeAttribute('jst-key');
  node.classList.add(`${name}-leave-from`, `${name}-leave-active`);
  nextFrame(() => {
    node.classList.remove(`${name}-leave-from`);
    node.classList.add(`${name}-leave-to`);
    afterTransition(node, () => {
      removeTransitionClasses(node, name, 'leave');
      remove();
    });
  });
}

function runMoveTransition(node) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) return;

  node.classList.add(`${name}-move`);
  afterTransition(node, () => node.classList.remove(`${name}-move`));
}

function insertRenderedNode(host, nextNode, beforeNode = null) {
  const inserted = cloneRenderedNode(nextNode);
  host.insertBefore(inserted, beforeNode);
  runEnterTransition(inserted);
  return inserted;
}

function removeRenderedNode(host, node) {
  runLeaveTransition(node, () => {
    if (node.parentNode === host) host.removeChild(node);
  });
  return node.parentNode !== host;
}

function escapeCssIdentifier(value) {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(value);
  return String(value).replace(/["\\]/g, '\\$&');
}

function syncAttributes(currentElement, nextElement) {
  Array.from(currentElement.attributes).forEach(attr => {
    if (!nextElement.hasAttribute(attr.name)) currentElement.removeAttribute(attr.name);
  });

  Array.from(nextElement.attributes).forEach(attr => {
    if (currentElement.getAttribute(attr.name) !== attr.value) {
      currentElement.setAttribute(attr.name, attr.value);
    }
  });
}

const booleanPropertyAttributes = {
  readOnly: 'readonly',
}

function booleanPropertyValue(element, name) {
  const attrName = booleanPropertyAttributes[name] || name.toLowerCase();
  if (!element.hasAttribute(attrName)) return false;
  const value = element.getAttribute(attrName);
  return value !== 'false' && value !== '0';
}

function syncBooleanProperty(currentElement, nextElement, name) {
  if (!(name in currentElement)) return;
  const value = booleanPropertyValue(nextElement, name);
  if (currentElement[name] !== value) currentElement[name] = value;
}

function syncBooleanPropertyIfDeclared(currentElement, nextElement, name) {
  const attrName = booleanPropertyAttributes[name] || name.toLowerCase();
  if (!nextElement.hasAttribute(attrName)) return;
  syncBooleanProperty(currentElement, nextElement, name);
}

function setLiveValue(element, value) {
  if (element.value !== value) element.value = value;
}

function syncFormProperties(currentElement, nextElement) {
  if (currentElement.nodeType !== Node.ELEMENT_NODE) return;

  const tagName = currentElement.tagName;

  if (tagName === 'INPUT') {
    if (nextElement.hasAttribute('value')) setLiveValue(currentElement, nextElement.getAttribute('value'));
    syncBooleanPropertyIfDeclared(currentElement, nextElement, 'checked');
  } else if (tagName === 'TEXTAREA') {
    if (currentElement.defaultValue !== nextElement.defaultValue) setLiveValue(currentElement, nextElement.value);
  } else if (tagName === 'SELECT') {
    if (nextElement.hasAttribute('value')) setLiveValue(currentElement, nextElement.getAttribute('value'));
  } else if (tagName === 'OPTION') {
    syncBooleanPropertyIfDeclared(currentElement, nextElement, 'selected');
  }

  ['disabled', 'required', 'readOnly', 'multiple'].forEach(prop => {
    syncBooleanProperty(currentElement, nextElement, prop);
  });
}

function cloneRenderedNode(nextNode) {
  const clone = nextNode.cloneNode(true);

  const syncTree = (current, next) => {
    if (current.nodeType !== Node.ELEMENT_NODE || next.nodeType !== Node.ELEMENT_NODE) return;
    syncFormProperties(current, next);

    const currentChildren = Array.from(current.childNodes);
    const nextChildren = Array.from(next.childNodes);
    nextChildren.forEach((nextChild, index) => {
      if (currentChildren[index]) syncTree(currentChildren[index], nextChild);
    });
  };

  syncTree(clone, nextNode);
  return clone;
}

function morphNode(currentNode, nextNode) {
  if (!nodesAreCompatible(currentNode, nextNode)) {
    const replacement = cloneRenderedNode(nextNode);
    currentNode.replaceWith(replacement);
    runEnterTransition(replacement);
    return;
  }

  if (currentNode.nodeType === Node.TEXT_NODE || currentNode.nodeType === Node.COMMENT_NODE) {
    if (currentNode.nodeValue !== nextNode.nodeValue) currentNode.nodeValue = nextNode.nodeValue;
    return;
  }

  // jst-preserve freezes a node against morph entirely: its attributes, form
  // properties, and whole subtree are left as they are. This is a stronger
  // opt-out than the managed-element boundary below, which still syncs its own
  // attributes, so this return sits ABOVE syncAttributes on purpose: the point
  // is to keep an attribute that legitimately changes each render (a signed
  // iframe src) or client state the DOM does not capture (media playback, a
  // canvas, a third-party widget) from being reconciled away (#74). Pairs with
  // jst-key so an unkeyed sibling shift cannot mismatch and replace the node.
  if (currentNode.hasAttribute('jst-preserve')) return;

  syncAttributes(currentNode, nextNode);
  syncFormProperties(currentNode, nextNode);
  // Managed elements render their own children; slot elements hold projected
  // author content. Neither should have its children morphed from the parent's
  // output. The early return is below syncAttributes on purpose: syncAttributes
  // carries this render's fresh `jst-bound`/`jst-bind-N` markers (and attribute
  // props) onto the existing managed child, so the parent's #applyBindings pass
  // re-applies its `.prop=`/event bindings to the child — flowing updated data
  // into a nested managed component's props on a parent re-render — without
  // touching the child's own DOM. Do not hoist this return above syncAttributes.
  if (isManagedCustomElement(currentNode) || isSlotElement(currentNode)) return;
  morphChildren(currentNode, nextNode);
}

function morphChildren(host, nextParent) {
  const nextNodes = Array.from(nextParent.childNodes);
  let index = 0;

  while (index < nextNodes.length || index < host.childNodes.length) {
    const currentNode = host.childNodes[index];
    const nextNode = nextNodes[index];

    if (!nextNode) {
      if (!removeRenderedNode(host, currentNode)) index++;
      continue;
    }

    if (!currentNode) {
      insertRenderedNode(host, nextNode);
      index++;
      continue;
    }

    const nextKey = getNodeKey(nextNode);
    if (nextKey != null && getNodeKey(currentNode) !== nextKey) {
      const keyedMatch = findKeyedChild(host, nextNode, index + 1);
      if (keyedMatch) {
        host.insertBefore(keyedMatch, currentNode);
        morphNode(keyedMatch, nextNode);
        runMoveTransition(keyedMatch);
      } else {
        insertRenderedNode(host, nextNode, currentNode);
      }
      index++;
      continue;
    }

    if (getNodeKey(currentNode) != null && nextKey == null && !nodesAreCompatible(currentNode, nextNode)) {
      insertRenderedNode(host, nextNode, currentNode);
      index++;
      continue;
    }

    if (!nodesAreCompatible(currentNode, nextNode)) {
      const replacement = cloneRenderedNode(nextNode);
      host.replaceChild(replacement, currentNode);
      runEnterTransition(replacement);
      index++;
      continue;
    }

    morphNode(currentNode, nextNode);
    index++;
  }
}

function applyRenderedHtml(host, html) {
  if (!canMorphDom(host)) {
    host.innerHTML = html;
    return;
  }

  const template = document.createElement('template');
  template.innerHTML = html;
  morphChildren(host, template.content);
}

/**
 * Morph `target` to match `next`, preserving node identity where the structure
 * lines up: focus, scroll positions, and open/closed state survive; `jst-key`
 * attributes pair keyed children across reorders. The incoming HTML is the
 * source of truth for attributes and form values, except on a node marked
 * `jst-preserve`, which is frozen: its attributes and whole subtree are left
 * untouched (#74). This is the engine behind jst-nav's jst-swap="morph" (#66).
 *
 * `next` selects the style:
 *   - an HTML string, or a node whose childNodes are the desired result:
 *     children-style — target keeps its own tag/attributes, its children morph.
 *   - a single element whose tag matches target: element-style (outerHTML) —
 *     target's own attributes reconcile against that element too, then children
 *     morph. This is what lets a jst-select that yields the target element
 *     itself upgrade to a state-preserving morph instead of nesting (#68).
 */
export function morph(target, next) {
  if (!target || next == null) return;
  if (typeof next === 'string') { applyRenderedHtml(target, next); return; }
  if (!canMorphDom(target)) return;
  if (next.nodeType === Node.ELEMENT_NODE && nodesAreCompatible(target, next)) {
    morphNode(target, next);
    return;
  }
  if (next.childNodes) morphChildren(target, next);
}

const jsonLikePattern = /^(?:true|false|null|-?\d|\[|\{|")/

/**
 * Attributes arrive as strings. Values that look like JSON (numbers, booleans,
 * arrays, objects, quoted strings) are parsed so count="0" renders as a number.
 * Anything else stays a plain string. No eval involved.
 */
function parseAttributeValue(rawValue) {
  if (rawValue === null) return undefined
  const trimmed = rawValue.trim()
  if (!jsonLikePattern.test(trimmed)) return rawValue
  try { return JSON.parse(trimmed) } catch { return rawValue }
}

const bindingAttributePattern = /^jst-bind-(\d+)$/
const boundListeners = new WeakMap()
const modelListeners = new WeakMap()

/* ---------------------------------------------------------------------------
 * Handler helpers — called INSIDE a handler body, which since v0.6.0 is the
 * one handler shape everywhere (templates, native inline handlers,
 * addEventListener). They take the current `event`, so they work per-call with
 * no wrapper closure; state lives in a WeakMap keyed by element + event type
 * (+ delay), and removed elements take their state with them.
 *
 *   oninput="if (changed(event)) debounce(event, 300, () => search(this.value))"
 *   onkeydown="keys(event, { Enter: () => go(), 'Meta+k': () => palette() })"
 *   oncommand="commands(event, { '--save': save, '--revert': revert })"
 *
 * In template handler bodies they're in scope; elsewhere they're `JST.fn.*`
 * / module exports. preventDefault/stopPropagation need no helper — they're
 * native statements in the body: onclick="event.preventDefault(); save()".
 */

const combinatorState = new WeakMap()
function combinatorSlot(el) {
  let map = combinatorState.get(el)
  if (!map) combinatorState.set(el, map = new Map())
  return map
}

/**
 * Debounce: run `fn` once this event goes quiet for `ms`. State is per
 * element + event type + delay, so a 300ms validate and a 2s autosave on the
 * same input never collide.
 */
export function debounce(event, ms, fn) {
  const map = combinatorSlot(event.currentTarget ?? event.target)
  const key = `debounce|${event.type}|${ms}`
  clearTimeout(map.get(key))
  map.set(key, setTimeout(fn, ms))
}

/** Throttle guard: true on the leading edge, false inside the `ms` window. */
export function throttle(event, ms) {
  const map = combinatorSlot(event.currentTarget ?? event.target)
  const key = `throttle|${event.type}|${ms}`
  const now = Date.now()
  if (now - (map.get(key) || 0) < ms) return false
  map.set(key, now)
  return true
}

// changed() answers once per event: asking again for the same event returns
// the recorded answer instead of comparing (and shifting state) twice.
const changedAnswers = new WeakMap()

/**
 * Changed guard: true when the control's `value` differs from the value this
 * helper saw on the previous event for that control (the first comparison
 * uses the control's initial/default value, so a keyup that edited nothing
 * doesn't pass). Idempotent per event.
 */
export function changed(event) {
  if (changedAnswers.has(event)) return changedAnswers.get(event)
  const control = event.target
  const map = combinatorSlot(control)
  const key = `changed|${event.type}`
  const last = map.has(key) ? map.get(key) : (control.defaultValue ?? '')
  const answer = control.value !== last
  if (answer) map.set(key, control.value)
  changedAnswers.set(event, answer)
  return answer
}

/**
 * Key dispatch: keys(event, { Enter: fn, Escape: fn, 'Shift+Enter': fn2 }).
 * Held modifier keys prefix the key name in Ctrl+Alt+Meta+Shift order; a bare
 * key name matches regardless of held modifiers unless a prefixed entry wins.
 */
export function keys(event, map) {
  const combo = (event.ctrlKey ? 'Ctrl+' : '') + (event.altKey ? 'Alt+' : '')
    + (event.metaKey ? 'Meta+' : '') + (event.shiftKey ? 'Shift+' : '') + event.key
  const handler = map[combo] || map[event.key]
  return handler && handler(event)
}

/**
 * Command dispatch for the Invoker Commands API: a `commandfor` target that
 * handles several custom commands routes them without a hand-written switch.
 *
 *   oncommand="commands(event, { '--save': save, '--revert': revert })"
 *
 * Dispatches on event.command (the handler also receives the event, so
 * event.source is the invoking button); commands with no entry are ignored.
 */
export function commands(event, map) {
  const handler = map[event.command]
  return handler && handler(event)
}

/** The helper namespace published as JST.fn (and handed to templates). */
const combinators = { changed, debounce, throttle, keys, commands }

function parseEventDescriptor(descriptor) {
  const [eventName, ...modifiers] = descriptor.split('.');
  return { eventName, modifiers };
}

function valueFromModelControl(element, currentValue) {
  if (element instanceof HTMLInputElement && element.type === 'checkbox') {
    if (Array.isArray(currentValue)) {
      const next = currentValue.filter(value => String(value) !== element.value);
      if (element.checked) next.push(element.value);
      return next;
    }
    return element.checked;
  }

  if (element instanceof HTMLInputElement && element.type === 'radio') {
    return element.checked ? element.value : currentValue;
  }

  if (element instanceof HTMLSelectElement && element.multiple) {
    return Array.from(element.selectedOptions).map(option => option.value);
  }

  return element.value;
}

function syncModelControl(element, value) {
  if (element instanceof HTMLInputElement && element.type === 'checkbox') {
    const checked = Array.isArray(value)
      ? value.map(String).includes(element.value)
      : Boolean(value);
    if (element.checked !== checked) element.checked = checked;
    return;
  }

  if (element instanceof HTMLInputElement && element.type === 'radio') {
    const checked = value != null && String(value) === element.value;
    if (element.checked !== checked) element.checked = checked;
    return;
  }

  if (element instanceof HTMLSelectElement && element.multiple) {
    const selected = Array.isArray(value) ? value.map(String) : [];
    Array.from(element.options).forEach(option => {
      option.selected = selected.includes(option.value);
    });
    return;
  }

  if ('value' in element && element.value !== (value == null ? '' : String(value))) {
    element.value = value == null ? '' : String(value);
  }
}

// The only modifiers left: they configure listener REGISTRATION (addEventListener
// options / attach point), which a handler can't express from inside itself.
const registrationModifiers = new Set(['capture', 'passive', 'once', 'outside']);

// Removed-in-v0.5.0 behaviour modifiers → the handler-body statement that
// replaces each (v0.6.0 spellings).
const removedModifierHints = {
  prevent: 'onclick="event.preventDefault(); …"',
  stop: 'onclick="event.stopPropagation(); …"',
  self: 'onclick="if (event.target !== this) return; …"',
  debounce: 'oninput="debounce(event, 300, () => …)"',
  changed: 'oninput="if (changed(event)) …"',
  enter: 'onkeydown="keys(event, { Enter: () => … })"',
  escape: 'onkeydown="keys(event, { Escape: () => … })"',
  esc: 'onkeydown="keys(event, { Escape: () => … })"',
  tab: 'onkeydown="keys(event, { Tab: () => … })"',
  space: 'onkeydown="keys(event, { \' \': () => … })"',
  up: 'onkeydown="keys(event, { ArrowUp: () => … })"',
  down: 'onkeydown="keys(event, { ArrowDown: () => … })"',
  left: 'onkeydown="keys(event, { ArrowLeft: () => … })"',
  right: 'onkeydown="keys(event, { ArrowRight: () => … })"',
};

function assertRegistrationModifiers(eventName, modifiers) {
  for (const modifier of modifiers) {
    if (registrationModifiers.has(modifier)) continue;
    if (/^\d+$/.test(modifier)) continue;   // numeric tail of a removed .debounce.N — that error already points at debounce
    const hint = removedModifierHints[modifier];
    throw new Error(hint
      ? `JST: the .${modifier} event modifier was removed in v0.5.0 — write it in the handler body instead: ${hint}. Modifiers now only configure listener registration (.capture .passive .once .outside).`
      : `JST: on${eventName}.${modifier} — ".${modifier}" is not an event modifier. Modifiers configure listener registration only (.capture .passive .once .outside); everything else is plain JS in the handler body.`);
  }
}

/* ------------------------------------------------------- synthetic events */

// `reveal` — fires when the element scrolls into view. Wired whenever a
// handler binds onreveal: a shared IntersectionObserver dispatches a real
// CustomEvent('reveal', { detail: entry }) on the element each time it enters
// the viewport, so addEventListener('reveal', …) works like any other event.
export const syntheticEvents = new Set(['reveal']);

let revealObserver = null;
const revealObserved = new WeakSet();

function observeReveal(element) {
  if (revealObserved.has(element) || typeof IntersectionObserver === 'undefined') return;
  if (!revealObserver) {
    revealObserver = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (!entry.isIntersecting) return;
        if (!entry.target.isConnected) { unobserveReveal(entry.target); return; }
        entry.target.dispatchEvent(new CustomEvent('reveal', { detail: entry }));
      });
    });
  }
  revealObserved.add(element);
  revealObserver.observe(element);
}

function unobserveReveal(element) {
  if (!revealObserver || !revealObserved.has(element)) return;
  revealObserved.delete(element);
  revealObserver.unobserve(element);
}

function buildEventListener(element, descriptor, handler) {
  const { eventName, modifiers } = parseEventDescriptor(descriptor);
  assertRegistrationModifiers(eventName, modifiers);
  const modifierSet = new Set(modifiers);
  const options = {
    capture: modifierSet.has('capture'),
    passive: modifierSet.has('passive'),
    once: modifierSet.has('once'),
  };

  return {
    eventName,
    reveal: syntheticEvents.has(eventName) && eventName === 'reveal',
    target: modifierSet.has('outside') ? document : element,
    options,
    // The handler is a `function (event) { body }` — passing it straight to
    // addEventListener gives the native contract (`this` = the element).
    // `.outside` attaches to document but forwards `this` as the element,
    // which is the element the behaviour conceptually belongs to.
    listener: modifierSet.has('outside')
      ? function (event) {
          if (!element.contains(event.target)) return handler.call(element, event);
        }
      : handler,
  };
}

function applyBinding(element, { kind, name, value }) {
  if (kind === 'prop') {
    if (!Object.is(element[name], value)) element[name] = value
    return
  }

  const listeners = boundListeners.get(element) || {}
  if (listeners[name]) {
    listeners[name].target.removeEventListener(listeners[name].eventName, listeners[name].listener, listeners[name].options)
  }

  if (typeof value === 'function') {
    const binding = buildEventListener(element, name, value)
    binding.target.addEventListener(binding.eventName, binding.listener, binding.options)
    if (binding.reveal) observeReveal(element)
    listeners[name] = binding
    boundListeners.set(element, listeners)
    return binding
  } else {
    delete listeners[name]
  }

  boundListeners.set(element, listeners)
  return null
}

function applyModelBinding(host, element, propName, paramNames) {
  const previous = modelListeners.get(element);
  if (previous) element.removeEventListener(previous.eventName, previous.listener);

  if (!paramNames.includes(propName)) {
    console.warn(`JST: jst-model="${propName}" does not match a declared prop on <${host.tagName.toLowerCase()}>.`);
  }

  syncModelControl(element, host._jstGetParam(propName));

  const eventName = element instanceof HTMLSelectElement
    || (element instanceof HTMLInputElement && (element.type === 'checkbox' || element.type === 'radio'))
    ? 'change'
    : 'input';
  const listener = () => {
    host[propName] = valueFromModelControl(element, host._jstGetParam(propName));
  };
  element.addEventListener(eventName, listener);
  element.removeAttribute('jst-model');
  modelListeners.set(element, { eventName, listener });
}

export function registerCustomElementFromTemplate(templateElement) {
  const customElementName = templateElement.getAttribute('name')?.toLowerCase();
  const source = templateSource(templateElement);

  // Custom elements MUST have a hyphen in their name
  if (!customElementName || !customElementName.includes('-')) {
    console.error(`JST Error: "${customElementName}" is not a valid custom element name. It MUST contain a hyphen (e.g. jst-${customElementName}).`, source);
    return;
  }

  if (templateElement.__jstRegisteredName === customElementName) {
    return customElements.get(customElementName);
  }

  let renderFunction;
  let compiledRender;
  try {
    renderFunction = compileTemplateRenderingFunction(templateElement);
    compiledRender = new Function(
      ...renderFunction.functionParams,
      'el',
      'slot',
      'onDisconnect',
      '__esc',
      '__bind',
      'url',
      'once',
      'trustedHTML',
      // Handler helpers, in scope inside handler bodies.
      'changed',
      'debounce',
      'throttle',
      'keys',
      'commands',
      renderFunction.functionBody,
    );
  } catch (error) {
    if (/runtime-only build/.test(String(error?.message ?? error))) throw error;
    const elementClass = defineCompileErrorElement(customElementName, error, source);
    if (elementClass) templateElement.__jstRegisteredName = customElementName;
    return elementClass;
  }

  const elementClass = defineCustomElementFromRender({
    customElementName,
    paramNames: renderFunction.functionParams,
    attributeToParam: renderFunction.paramMap,
    renderFunctionBody: renderFunction.functionBody,
    source,
    createRenderFunction: () => compiledRender,
  });

  if (elementClass) templateElement.__jstRegisteredName = customElementName;
  return elementClass;
}

function compileErrorHtml(customElementName, error) {
  return `<pre class="jst-error" role="alert">JST Compile Error in &lt;${escapeHtml(customElementName)}&gt;\n${escapeHtml(error?.stack || error?.message || error)}</pre>`;
}

function defineCompileErrorElement(customElementName, error, source) {
  if (templates.has(customElementName)) {
    console.warn(`JST: Duplicate template name "${customElementName}" ignored.`, source);
    return customElements.get(customElementName);
  }

  templates.set(customElementName, {
    functionParams: [],
    paramMap: {},
    source,
    error,
  });

  console.error(`JST Compile Error in <${customElementName}>:`, error);

  if (customElements.get(customElementName)) {
    console.warn(`JST: Custom element <${customElementName}> is already registered.`, source);
    return customElements.get(customElementName);
  }

  const CustomElementClass = class extends HTMLElement {
    connectedCallback() {
      this.innerHTML = compileErrorHtml(customElementName, error);
    }
  };

  customElements.define(customElementName, CustomElementClass);
  return CustomElementClass;
}

export function registerPrecompiledTemplate(customElementName, paramNames, attributeToParam, renderFunction, source = 'precompiled') {
  if (!customElementName || !customElementName.includes('-')) {
    console.error(`JST Error: "${customElementName}" is not a valid custom element name. It MUST contain a hyphen (e.g. jst-${customElementName}).`, source);
    return;
  }

  return defineCustomElementFromRender({
    customElementName: customElementName.toLowerCase(),
    paramNames,
    attributeToParam,
    renderFunctionBody: renderFunction.toString(),
    source,
    createRenderFunction: () => renderFunction,
  });
}

function defineCustomElementFromRender({
  customElementName,
  paramNames,
  attributeToParam,
  renderFunctionBody,
  source,
  createRenderFunction,
}) {
  if (templates.has(customElementName)) {
    console.warn(`JST: Duplicate template name "${customElementName}" ignored.`, source);
    return customElements.get(customElementName);
  }

  templates.set(customElementName, {
    functionParams: paramNames,
    paramMap: attributeToParam,
    source,
  });

  if (customElements.get(customElementName)) {
    console.warn(`JST: Custom element <${customElementName}> is already registered.`, source);
    return customElements.get(customElementName);
  }

  let compiledRender = null;

  const CustomElementClass = class extends HTMLElement {
    #params = {};
    #renderQueued = false;
    #hasRendered = false;
    #slotContent = null;
    #slotContentDetached = false;
    #rendering = false;
    #slotObserver = null;
    #disconnectCleanups = new Set();
    #onceKeys = new Set();
    #connectionEpoch = 0;
    #outsideTracked = new WeakSet();

    static get observedAttributes() {
      return Object.keys(attributeToParam);
    }

    connectedCallback() {
      // Each connection is its own epoch; deferred once() setups captured under
      // a stale epoch (e.g. a synchronous disconnect+reconnect) are discarded.
      this.#connectionEpoch++;
      this.#captureSlotContent();
      this.#observeSlotMutations();
      this.#upgradeProperties();
      this.requestRender();
    }

    disconnectedCallback() {
      this.#slotObserver?.disconnect();
      this.#slotObserver = null;

      this.#disconnectCleanups.forEach(cleanup => {
        try {
          cleanup();
        } catch (error) {
          console.error(`JST disconnect cleanup error in <${customElementName}>:`, error);
        }
      });
      this.#disconnectCleanups.clear();
      this.#onceKeys.clear();
    }

    attributeChangedCallback(name, oldValue, newValue) {
      if (oldValue === newValue) return;
      this.#params[attributeToParam[name]] = parseAttributeValue(newValue);
      if (this.isConnected) this.requestRender();
    }

    /** Dispatch a bubbling CustomEvent. Data out: parents/pages listen for these. */
    emit(eventName, detail) {
      return this.dispatchEvent(new CustomEvent(eventName, { detail, bubbles: true, composed: true }));
    }

    requestRender() {
      if (this.#renderQueued) return;
      this.#renderQueued = true;

      queueMicrotask(() => {
        this.#renderQueued = false;
        if (this.isConnected) this.render();
      });
    }

    render() {
      if (!this.isConnected) return;

      const bindings = [];

      try {
        compiledRender = compiledRender || createRenderFunction();

        const html = compiledRender.call(
          this,
          ...paramNames.map(param => this.#params[param]),
          this,
          createSlotPlaceholder,
          cleanup => this.#registerDisconnectCleanup(cleanup),
          escapeHtml,
          (kind, name, value) => ` jst-bound jst-bind-${bindings.push({ kind, name, value }) - 1}=""`,
          url,
          (key, setupFn) => this.#runOnce(key, setupFn),
          trustedHTML,
          changed,
          debounce,
          throttle,
          keys,
          commands,
        );

        this.#slotObserver?.disconnect();
        this.#slotObserver = null;

        const applyDom = () => {
          this.#rendering = true;
          try {
            this.#detachSlotContent();
            applyRenderedHtml(this, html);
            this.#applyBindings(bindings);
            this.#applyModelBindings();
            this.#fillSlots();
          } finally {
            this.#rendering = false;
            this.#observeSlotMutations();
          }
        };

        // Opt-in per instance: `<my-el view-transition>` animates this instance's
        // re-renders via the View Transition API. Skipped on the first paint
        // (nothing to animate from), where the API is unsupported, and on a hidden
        // document — and an abort degrades quietly to an instant render rather than
        // surfacing the transition's rejection as an unhandled error (#43).
        const canViewTransition = this.#hasRendered
          && this.getAttribute('view-transition') != null
          && typeof document.startViewTransition === 'function'
          && document.visibilityState !== 'hidden';
        if (canViewTransition) {
          let transition;
          try { transition = document.startViewTransition(applyDom); }
          catch { applyDom(); }
          transition?.ready?.catch(() => {});
          transition?.finished?.catch(() => {});
        } else {
          applyDom();
        }
        this.#hasRendered = true;
      } catch (e) {
        console.error(`JST Render Error in <${customElementName}>:`, e);
        console.groupCollapsed('--- Problematic Generated Code ---');
        console.log(renderFunctionBody);
        console.groupEnd();
        if (config.dev) this.#showDevError(e);
      }
    }

    _jstGetParam(param) { return this.#params[param]; }

    _jstSetParam(param, value) {
      const previous = this.#params[param];
      this.#params[param] = value;
      const isMutableReference = value !== null && (typeof value === 'object' || typeof value === 'function');
      if (Object.is(previous, value) && !isMutableReference) return;
      this.requestRender();
    }

    #registerDisconnectCleanup(cleanup) {
      if (typeof cleanup !== 'function') return cleanup;
      this.#disconnectCleanups.add(cleanup);
      return cleanup;
    }

    #runOnce(key, setupFn) {
      if (this.#onceKeys.has(key)) return undefined;
      if (typeof setupFn !== 'function') return undefined;

      this.#onceKeys.add(key);

      // The template body runs before this render commits, so the component's
      // own rendered DOM and projected slots don't exist yet. Defer setup to a
      // microtask so it sees the committed DOM, and register whatever it returns
      // as disconnect cleanup, so callers never have to wire teardown by hand.
      const epoch = this.#connectionEpoch;
      queueMicrotask(() => {
        if (!this.isConnected || this.#connectionEpoch !== epoch || !this.#onceKeys.has(key)) return;
        try {
          const cleanup = setupFn();
          if (typeof cleanup === 'function') this.#registerDisconnectCleanup(cleanup);
        } catch (error) {
          this.#onceKeys.delete(key);
          console.error(`JST once("${key}") setup error in <${customElementName}>:`, error);
          if (config.dev) this.#showDevError(error);
        }
      });

      return undefined;
    }

    #showDevError(error) {
      this.innerHTML = `<pre class="jst-error" role="alert">JST Render Error in &lt;${escapeHtml(customElementName)}&gt;\n${escapeHtml(error?.stack || error?.message || error)}</pre>`;
    }

    /**
     * A property assigned before the element upgrades lands as an own property
     * that shadows the prototype accessor. Re-route it through the setter.
     */
    #upgradeProperties() {
      paramNames.forEach(param => {
        if (Object.prototype.hasOwnProperty.call(this, param)) {
          const value = this[param];
          delete this[param];
          this[param] = value;
        }
      });
    }

    /**
     * On first connect the element's children are the author's content.
     * Capture references so the template can project them via $(slot()).
     * The nodes stay in the document until the first render so they remain
     * reachable (getElementById, listeners) in the meantime.
     */
    #captureSlotContent() {
      if (this.#slotContent || !this.childNodes) return;

      const named = new Map();
      const defaultNodes = [];

      Array.from(this.childNodes).forEach(node => {
        const slotName = node.nodeType === Node.ELEMENT_NODE ? node.getAttribute('slot') : null;
        if (slotName) {
          if (!named.has(slotName)) named.set(slotName, []);
          named.get(slotName).push(node);
        } else {
          defaultNodes.push(node);
        }
      });

      this.#slotContent = { defaultNodes, named };
    }

    #observeSlotMutations() {
      if (this.#slotObserver || typeof MutationObserver === 'undefined') return;

      this.#slotObserver = new MutationObserver(mutations => {
        if (this.#rendering) return;

        mutations.forEach(mutation => {
          mutation.addedNodes.forEach(node => {
            if (node.nodeType !== Node.ELEMENT_NODE && node.nodeType !== Node.TEXT_NODE) return;
            if (!this.#slotContent) this.#captureSlotContent();

            const slotName = node.nodeType === Node.ELEMENT_NODE ? node.getAttribute('slot') : null;
            if (slotName) {
              if (!this.#slotContent.named.has(slotName)) this.#slotContent.named.set(slotName, []);
              const nodes = this.#slotContent.named.get(slotName);
              if (!nodes.includes(node)) nodes.push(node);
            } else if (!this.#slotContent.defaultNodes.includes(node)) {
              this.#slotContent.defaultNodes.push(node);
            }

            this.#rendering = true;
            try {
              this.#placeSlotContent(slotName);
            } finally {
              this.#rendering = false;
            }
          });
        });
      });

      this.#slotObserver.observe(this, { childList: true });
    }

    /**
     * Detach the captured author content right before the first morph, so the
     * morph never mutates author nodes and #fillSlots can re-project them.
     * Runs synchronously inside render(): no observable detached window.
     */
    #detachSlotContent() {
      if (this.#slotContentDetached || !this.#slotContent) return;
      this.#slotContentDetached = true;

      this.#slotContent.defaultNodes.forEach(node => node.remove?.());
      this.#slotContent.named.forEach(nodes => nodes.forEach(node => node.remove?.()));
    }

    #applyBindings(bindings) {
      if (!bindings.length || typeof this.querySelectorAll !== 'function') return;

      // Binding markers are stripped synchronously after every render, so any
      // marker present right now was emitted by this render's binding table —
      // including markers inside a nested component's light DOM.
      this.querySelectorAll('[jst-bound]').forEach(element => {
        Array.from(element.attributes).forEach(attribute => {
          const match = attribute.name.match(bindingAttributePattern);
          if (!match) return;

          element.removeAttribute(attribute.name);
          const binding = bindings[Number(match[1])];
          if (!binding) return;
          const applied = applyBinding(element, binding);
          // `.outside` listeners live on `document`, so they outlive the host
          // unless explicitly removed. Element-targeted listeners die with their
          // element; document-targeted ones leak and fire after disconnect.
          // Register one cleanup per element that strips its document listeners.
          if (applied && (applied.target === document || applied.reveal) && !this.#outsideTracked.has(element)) {
            this.#outsideTracked.add(element);
            this.#registerDisconnectCleanup(() => {
              const current = boundListeners.get(element);
              if (!current) return;
              Object.values(current).forEach(b => {
                if (b.target === document) {
                  b.target.removeEventListener(b.eventName, b.listener, b.options);
                }
                // Reveal observation holds a strong ref in the shared
                // IntersectionObserver — release it with the host.
                if (b.reveal) unobserveReveal(element);
              });
            });
          }
        });

        element.removeAttribute('jst-bound');
      });
    }

    #applyModelBindings() {
      if (typeof this.querySelectorAll !== 'function') return;

      this.querySelectorAll('[jst-model]').forEach(element => {
        applyModelBinding(this, element, element.getAttribute('jst-model'), paramNames);
      });
    }

    #fillSlots() {
      if (typeof this.querySelectorAll !== 'function') return;

      this.querySelectorAll('jst-slot').forEach(slotElement => {
        if (slotElement.__jstFilled) return;
        slotElement.__jstFilled = true;

        this.#placeSlotContent(slotElement.getAttribute('name'));
      });
    }

    #placeSlotContent(name) {
      if (typeof this.querySelector !== 'function') return;
      const selector = name ? `jst-slot[name="${escapeCssIdentifier(name)}"]` : 'jst-slot:not([name])';
      const slotElement = this.querySelector(selector);
      if (!slotElement) return;

      const nodes = (name
        ? this.#slotContent?.named.get(name)
        : this.#slotContent?.defaultNodes) || [];

      if (nodes.length) slotElement.replaceChildren(...nodes);
    }
  };

  // Each declared prop becomes a real property: el.items = [...] re-renders.
  paramNames.forEach(param => {
    if (Object.prototype.hasOwnProperty.call(CustomElementClass.prototype, param)) {
      console.warn(`JST: Prop "${param}" on <${customElementName}> clashes with a component member and will not get a property accessor.`);
      return;
    }

    Object.defineProperty(CustomElementClass.prototype, param, {
      configurable: true,
      enumerable: true,
      get() { return this._jstGetParam(param); },
      set(value) { this._jstSetParam(param, value); },
    });
  });

  customElements.define(customElementName, CustomElementClass);
  if (config.dev) console.log(`JST: Registered <${customElementName}>`, source);
  return CustomElementClass;
}

export function initializeTemplates() {
  if (templatesInitialized) return templates;
  templatesInitialized = true;
  announceVersion();

  document.querySelectorAll('script[type="jst"]').forEach(registerCustomElementFromTemplate);
  observeNewTemplates();
  scanForMissingTemplates(document.documentElement);

  return templates;
}

/**
 * Templates that arrive after initial load (e.g. inside an htmx/fetch fragment)
 * register automatically, so a server can ship component definitions on demand.
 */
function observeNewTemplates() {
  if (templateObserver || typeof MutationObserver === 'undefined') return;
  if (config.autoRegister === false
    && typeof config.resolveTemplate !== 'function') return;

  templateObserver = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      mutation.addedNodes.forEach(node => {
        if (node.nodeType !== Node.ELEMENT_NODE) return;
        if (config.autoRegister !== false) {
          if (node.matches?.('script[type="jst"]')) registerCustomElementFromTemplate(node);
          node.querySelectorAll?.('script[type="jst"]').forEach(registerCustomElementFromTemplate);
        }
        scanForMissingTemplates(node);
      });
    });
  });

  const root = config.autoRegisterRoot || document.documentElement;
  templateObserver.observe(root, { childList: true, subtree: true });
}

/* ------------------------------------------------ body-HTML synthetic events */

// Native events in plain body HTML are the browser's business: it wires
// on<event> attributes for its own event names. Everything ELSE — component
// custom events (onitem-selected) and JST's synthetic events (onreveal) — can
// only fire if JST evaluates the attribute string, exactly the thing a strict
// CSP forbids for inline handlers. So it's opt-in:
//
//   JST.configure({ unsafeInlineHandlers: true })
//
// With the flag on, JST wires every on* attribute the platform does NOT
// implement (checked via `'on'+name in element`, so browser-owned handlers
// are never double-wired). The value is evaluated with the native contract
// (function body, `event` in scope, `this` = the element). Never enable this
// on pages that interpolate untrusted data into HTML: it re-opens the
// injected-handler hole a strict CSP exists to close (the script-gadget rule —
// see docs). Under a CSP that blocks 'unsafe-eval' the Function constructor
// throws loudly rather than silently.
const inlineWired = new WeakSet();
let inlineObserver = null;
const inlineHandlerAttribute = /^on[a-z]/;

function wireInlineBodyHandlers(root = document) {
  if (!config.unsafeInlineHandlers || typeof document === 'undefined') return;

  const wire = (element) => {
    if (inlineWired.has(element)) return;
    inlineWired.add(element);
    for (const name of element.getAttributeNames()) {
      if (!inlineHandlerAttribute.test(name)) continue;
      if (name in element) continue;   // platform-implemented: the browser owns it
      const body = element.getAttribute(name);
      if (!body || !body.trim()) continue;
      let handler;
      try {
        handler = new Function('event', body);
      } catch (error) {
        console.error(`JST: invalid ${name} handler body on`, element, error);
        continue;
      }
      const type = name.slice(2);
      element.addEventListener(type, handler);
      if (type === 'reveal') observeReveal(element);
    }
  };

  const scan = (node) => {
    if (!node || typeof node.querySelectorAll !== 'function') return;
    if (node.nodeType === 1) wire(node);
    node.querySelectorAll('*').forEach(wire);
  };

  scan(root.documentElement || root);

  if (!inlineObserver && typeof MutationObserver !== 'undefined') {
    inlineObserver = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        mutation.addedNodes.forEach(node => { if (node.nodeType === 1) scan(node); });
        // Release reveal observation for removed subtrees (the shared
        // IntersectionObserver holds strong refs).
        mutation.removedNodes.forEach(node => {
          if (node.nodeType !== 1) return;
          if (node.matches && node.matches('[onreveal]')) unobserveReveal(node);
          if (typeof node.querySelectorAll === 'function') node.querySelectorAll('[onreveal]').forEach(unobserveReveal);
        });
      }
    });
    inlineObserver.observe(root.documentElement || root, { childList: true, subtree: true });
  }
}

export function resetJstForTests() {
  templates.clear();
}

/**
 * The ES-module exports are canonical. This publishes a reduced `window.JST`
 * global — the handful of entry points a non-module or server-streamed page
 * needs (configure, trustedHTML/url helpers, register/init) plus the live
 * `config` object — without re-exposing internal state like the template map.
 */
function publishJstApi() {
  if (typeof window === 'undefined') return;

  window.JST = {
    ...window.JST,
    version,
    configure,
    trustedHTML,
    url,
    registerCustomElementFromTemplate,
    registerPrecompiledTemplate,
    initializeTemplates,
    morph,
    config,
    fn: combinators,
  };
}

publishJstApi();
initializeTemplates();
