/*! JST global build v0.2.3 — generated by tools/build_global.mjs. Do not edit by hand. */
/*! © Brent Jacobs · https://github.com/br3nt/jst · MIT */
(() => {
'use strict';
/* ===== tokens.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
class Token { }

class Escaped$Token extends Token {
  toString() { return `${Escaped$Token.name} {}` }
}

class WhitespaceToken extends Token {
  whitespace

  constructor(whitespace) {
    super()
    this.whitespace = whitespace
  }

  toString() { return `${WhitespaceToken.name} {}` }
}

class JsIdentifierToken extends Token {
  identifier

  constructor(identifier) {
    super()
    this.identifier = identifier
  }

  toString() { return `${JsIdentifierToken.name} { identifier=${this.identifier} }` }
}

class JsExpressionToken extends Token {
  expression

  constructor(expression) {
    super()
    this.expression = expression
  }

  toString() { return `${JsExpressionToken.name} { expression=${this.expression} }` }
}

class JsCodeToken extends Token {
  code

  constructor(code) {
    super()
    this.code = code
  }

  toString() { return `${JsCodeToken.name} { code=${this.code} }` }
}

class HtmlToken extends Token {
  html

  constructor(html) {
    super()
    this.html = html
  }

  toString() { return `${HtmlToken.name} { html=${this.html} }` }
}

class EndOfInputToken extends Token {


  toString() { return `${EndOfInputToken.name} {}` }

}
/* namespace shim for `import * as Tokens from './tokens.js'` */
const Tokens = { Token, Escaped$Token, WhitespaceToken, JsIdentifierToken, JsExpressionToken, JsCodeToken, HtmlToken, EndOfInputToken };
/* ===== input_reader.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
class InputReader {
  #input;
  #position = 0;
  #line = 1;
  #col = 0;

  get position() { return this.#position; }
  get line() { return this.#line; }
  get col() { return this.#col; }

  constructor(input) {
    this.#input = input
  }

  next() {
    const ch = this.#input.charAt(this.#position++);
    if (ch == "\n") { this.#line++; this.#col = 0; } else this.#col++;
    return ch
  }

  peek() { return this.#input.charAt(this.position); }

  peekNext() { return this.#input.charAt(this.position + 1); }

  peekAt(offset) { return this.#input.charAt(this.position + offset); }

  startsWith(str) { return this.#input.startsWith(str, this.position); }

  endOfInput() { return this.peek() === ''; }

  croak(msg) { throw new Error(`${msg} (${this.line}:${this.col})`); }

  readWhile(predicate) {
    const startPosition = this.position;
    while (predicate(this.peek(), this.peekNext()) && !this.endOfInput()) this.next();
    return this.#input.substring(startPosition, this.position);
  }

  readUntilChar(ch) {
    const str = this.readWhile(chPeek => chPeek !== ch)
    return str;
  }

  skipChar(ch) {
    if (this.peek() !== ch) this.croak(`expected current char to be ${ch} but got ${this.peek()}`);
    this.next();
  }

  readBalanced(chOpen, chClose) {
    const startPosition = this.position;
    this.skipChar(chOpen);
    let depth = 1;
    const prev = { char: '', word: '' };

    while (!this.endOfInput() && depth > 0) {
      if (this.#skipJsAtom(prev)) continue;

      const ch = this.peek();

      if (ch === chOpen) depth += 1;
      else if (ch === chClose) depth -= 1;

      this.next();
      this.#advancePrev(prev, ch);
    }

    if (depth !== 0) this.croak(`Unbalanced ${chOpen}${chClose}`);

    const str = this.#input.substring(startPosition, this.position);
    return str;
  }

  #resetPrev(prev) {
    prev.char = '';
    prev.word = '';
  }

  #markValue(prev) {
    prev.char = ')';
    prev.word = '';
  }

  #advancePrev(prev, ch) {
    if (/\s/.test(ch)) return;
    prev.char = ch;
    prev.word = /[\w$]/.test(ch) ? prev.word + ch : '';
  }

  static #regexKeywords = new Set([
    'return',
    'typeof',
    'instanceof',
    'in',
    'of',
    'new',
    'delete',
    'void',
    'do',
    'else',
    'yield',
    'await',
    'case',
    'throw',
  ]);

  static #regexAllowedAfter({ char, word }) {
    if (char === '') return true;
    if (/[)\]'"`]/.test(char)) return false;
    if (/[\w$.]/.test(char)) return InputReader.#regexKeywords.has(word);
    return true;
  }

  #skipString(quote) {
    this.next();
    while (!this.endOfInput()) {
      const ch = this.peek();
      if (ch === '\\') {
        this.next();
        this.next();
        continue;
      }
      if (ch === quote) {
        this.next();
        return;
      }
      if (ch === '\n' || ch === '\r') return;
      this.next();
    }
  }

  #skipTemplateLiteral() {
    this.next();
    while (!this.endOfInput()) {
      const ch = this.peek();
      if (ch === '\\') {
        this.next();
        this.next();
        continue;
      }
      if (ch === '`') {
        this.next();
        return;
      }
      if (ch === '$' && this.peekNext() === '{') {
        this.next();
        this.next();
        this.#skipTemplateInterpolation();
        continue;
      }
      this.next();
    }
  }

  #skipTemplateInterpolation() {
    let depth = 1;
    const prev = { char: '', word: '' };

    while (!this.endOfInput() && depth > 0) {
      if (this.#skipJsAtom(prev)) continue;

      const ch = this.peek();
      if (ch === '{') depth += 1;
      else if (ch === '}') depth -= 1;

      this.next();
      this.#advancePrev(prev, ch);
    }
  }

  #skipLineComment() {
    while (!this.endOfInput() && this.peek() !== '\n' && this.peek() !== '\r') this.next();
  }

  #skipBlockComment() {
    this.next();
    this.next();
    while (!this.endOfInput()) {
      if (this.peek() === '*' && this.peekNext() === '/') {
        this.next();
        this.next();
        return;
      }
      this.next();
    }
  }

  #skipRegexLiteral() {
    this.next();
    let inCharClass = false;

    while (!this.endOfInput()) {
      const ch = this.peek();
      if (ch === '\\') {
        this.next();
        this.next();
        continue;
      }
      if (ch === '\n' || ch === '\r') return;
      if (ch === '[') inCharClass = true;
      else if (ch === ']') inCharClass = false;
      else if (ch === '/' && !inCharClass) {
        this.next();
        break;
      }
      this.next();
    }

    while (!this.endOfInput() && /[a-z]/i.test(this.peek())) this.next();
  }

  #skipJsAtom(prev) {
    const ch = this.peek();
    const next = this.peekNext();

    if (ch === '/' && next === '/') {
      this.#skipLineComment();
      this.#resetPrev(prev);
      return true;
    }
    if (ch === '/' && next === '*') {
      this.#skipBlockComment();
      this.#resetPrev(prev);
      return true;
    }
    if (ch === '/' && InputReader.#regexAllowedAfter(prev)) {
      this.#skipRegexLiteral();
      this.#markValue(prev);
      return true;
    }
    if (ch === "'" || ch === '"') {
      this.#skipString(ch);
      this.#markValue(prev);
      return true;
    }
    if (ch === '`') {
      this.#skipTemplateLiteral();
      this.#markValue(prev);
      return true;
    }

    return false;
  }

  readJsLine(isHtmlBoundary) {
    const startPosition = this.position;
    const prev = { char: '', word: '' };

    while (!this.endOfInput()) {
      if (this.#skipJsAtom(prev)) continue;

      const ch = this.peek();
      const next = this.peekNext();

      if (ch === '\n' || ch === '\r') break;
      if (ch === '$') break;
      if (isHtmlBoundary(ch, next)) {
        const isCloseTag = ch === '<' && next === '/';
        if (isCloseTag || !this.#prevIsValue(prev)) break;
      }

      this.next();
      this.#advancePrev(prev, ch);
    }

    return this.#input.substring(startPosition, this.position);
  }

  #prevIsValue(prev) {
    return /[)\]'"`\w$]/.test(prev.char);
  }

  readBalancedInner(chOpen, chClose) {
    const str = this.readBalanced(chOpen, chClose);
    const strippedStr = str.substr(1, str.length - 2);
    return strippedStr;
  }
}
/* ===== lexer.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
class Lexer {
  #input

  constructor(inputReader) {
    this.#input = inputReader;
  }

  get position() { return this.#input.position; }
  get line() { return this.#input.line; }
  get col() { return this.#input.col; }

  croak(msg) { return this.#input.croak(msg); }

  nextToken() {
    if (this.#input.endOfInput()) return new Tokens.EndOfInputToken();

    const peek = this.#input.peek();

    // 1. Check for JST Marker
    if (peek === '$') return this.parseJsToken();

    // 2. Check for Whitespace
    if (Lexer.isWhitespace(peek)) return this.readWhitespaceToken();

    // 3. Otherwise, it's HTML
    return this.readHtmlToken();
  }

  static isWhitespace(ch) {
    return /[ \t\n\r]/.test(ch)
  }

  readWhitespaceToken() {
    const str = this.#input.readWhile(Lexer.isWhitespace);
    return new Tokens.WhitespaceToken(str);
  }

  parseJsToken() {
    this.#input.skipChar('$');
    const peek = this.#input.peek();

    switch (peek) {
      case '$': return this.readEscaped$Token();
      case '(': return this.readJsExpressionToken();
      case '{': return this.readJsBlockToken();
    }

    // Line-based directive ($ const ...) or Identifier ($id)
    if (peek === ' ' || Lexer.isWhitespace(peek)) {
      return this.readJsLineToken();
    }

    if (Lexer.isJsIdentifierStart(peek)) {
      return this.readJsIdentifierToken();
    }

    return this.croak(`Unexpected character after $: ${peek}`);
  }

  readJsIdentifierToken() {
    const str = this.#input.next() + this.#input.readWhile(Lexer.isJsIdentifierContinue);
    return new Tokens.JsIdentifierToken(str);
  }

  readJsLineToken() {
    // Skip leading space after $ if it exists
    if (this.#input.peek() === ' ') this.#input.next();

    const str = this.#input.readJsLine(
      (ch, chNext) => Lexer.isHtmlTagStart(ch, chNext) || Lexer.isHtmlTagEnd(ch, chNext),
    );
    return new Tokens.JsCodeToken(str);
  }

  readHtmlToken() {
    let str = '';

    while (!this.#input.endOfInput()) {
      if (this.#input.peek() === '$') break;

      if (this.startsHtmlComment()) {
        str += this.readHtmlComment();
        continue;
      }

      str += this.#input.next();
    }

    return new Tokens.HtmlToken(str);
  }

  readJsExpressionToken() {
    const str = this.#input.readBalancedInner('(', ')');
    return new Tokens.JsExpressionToken(str);
  }

  readJsBlockToken() {
    const str = this.#input.readBalancedInner('{', '}');
    return new Tokens.JsCodeToken(str);
  }

  readEscaped$Token() {
    this.#input.skipChar('$');
    return new Tokens.Escaped$Token();
  }

  static isJsIdentifierStart(ch) {
    return /^[$_\p{ID_Start}]$/u.test(ch);
  }

  static isJsIdentifierContinue(ch) {
    return /^[$\u200c\u200d\p{ID_Continue}]$/u.test(ch);
  }

  static isHtmlTagStart(ch, chNext) {
    return ch === '<' && /[a-z]/i.test(chNext);
  }

  static isHtmlTagEnd(ch, chNext) {
    return ch === '<' && chNext === '/';
  }

  startsHtmlComment() {
    return this.#input.peek() === '<'
      && this.#input.peekAt(1) === '!'
      && this.#input.peekAt(2) === '-'
      && this.#input.peekAt(3) === '-';
  }

  readHtmlComment() {
    let str = '';

    while (!this.#input.endOfInput()) {
      const ch = this.#input.next();
      str += ch;

      if (ch === '-' && this.#input.peek() === '-' && this.#input.peekAt(1) === '>') {
        str += this.#input.next();
        str += this.#input.next();
        break;
      }
    }

    return str;
  }
}
/* ===== parser.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
function parseTemplateScript(script) {
  const lexer = new Lexer(new InputReader(script))

  const tokens = []
  let token = lexer.nextToken()

  while (!(token instanceof EndOfInputToken)) {
    tokens.push(token)
    token = lexer.nextToken()
  }

  return new TemplateTokens(tokens)
}

class TemplateTokens {
  #tokens

  constructor(tokens) {
    this.#tokens = tokens
  }

  get tokens() { return this.#tokens }
}
/* ===== interpreter.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
/**
 * Consecutive `$ line` code directives (and the whitespace between them) merge
 * into one code block so multi-line statements compile as a unit. Interpolation
 * tokens ($(expr), $identifier) are output instructions and never merge.
 */
function mergeJsTokens(templateTokens) {
  const processedTokens = []

  for (let i = 0; i < templateTokens.length; i++) {
    const token = templateTokens[i]
    const last = processedTokens[processedTokens.length - 1]

    if (token instanceof JsCodeToken && last instanceof JsCodeToken) {
      last.code += ' ' + token.code
      continue
    }

    const isWhitespaceOnly = token instanceof WhitespaceToken
      || (token instanceof HtmlToken && !/[^\s]/.test(token.html))

    if (isWhitespaceOnly) {
      const next = templateTokens[i + 1]
      const ws = token.whitespace ?? token.html

      if (last instanceof JsCodeToken && next instanceof JsCodeToken) {
        last.code += ws
        continue
      }

      processedTokens.push(token instanceof WhitespaceToken ? token : new WhitespaceToken(token.html))
      continue
    }

    processedTokens.push(token)
  }

  return processedTokens
}

// Tag-position binding attributes whose value is a single $(…) expression:
//   `.prop="$(expr)"`     assigns the value as a JS property after morphing
//   `onevent="$(fn)"`     attaches the value with addEventListener after morphing
// Event handlers use the native `on<event>` attribute name with an optional
// dotted modifier tail (`onclick.stop`, `onkeydown.enter.prevent`); the `on`
// prefix is stripped to recover the event descriptor. `on*` is reserved for
// handlers: the opener matches any `on…` name (not just valid ones) so an invalid
// handler — an event name that does not start with a letter, e.g. `on3d-ready` —
// fails loud instead of silently degrading to a literal attribute.
const bindingNamePattern = '(\\.[a-zA-Z_$][\\w$-]*(?:\\.[\\w$-]+)*|on[\\w$-]+(?:\\.[\\w$-]+)*)'
// At the very end of an HTML chunk: a valid opener, immediately followed by the
// $(…) expression token (which split the chunk here).
const bindingTailPattern = new RegExp(`(^|\\s)${bindingNamePattern}\\s*=\\s*(["'])$`)
// The same opener anywhere in the chunk — used to reject values that are not a
// lone $(…) expression (leading text, or raw inline JavaScript in an on* handler).
const bindingOpenerPattern = new RegExp(`(^|\\s)${bindingNamePattern}\\s*=\\s*(["'])`, 'g')
// A well-formed event handler name: `on` + a letter, then word/$/- chars, then an
// optional dotted modifier tail.
const validEventName = /^on[a-zA-Z][\w$-]*(?:\.[\w$-]+)*$/
// Legacy `@event="$(fn)"` syntax (removed): detect and point at the replacement.
const legacyEventTailPattern = /(^|\s)@([a-zA-Z][\w$-]*(?:\.[\w$-]+)*)\s*=\s*["']$/

function classifyBindingName(rawName) {
  if (rawName[0] === '.') return { kind: 'prop', name: rawName.slice(1) }
  return { kind: 'event', name: rawName.slice(2) }
}

// Binding openers are only meaningful in tag-attribute position. Tag/quote state
// is tracked ACROSS chunks (a `$(…)` value splits one element's start tag into
// several HtmlTokens, so the opening `<` of a later binding lives in an earlier
// chunk), and a `>` inside a quoted attribute value does not close the tag. This
// lets an `on…="…"` / `.x="…"` sequence sitting in template *text* be left as
// literal text rather than misread as a binding, while still recognising the 2nd,
// 3rd, … binding on the same element.
function advanceTagState(state, html) {
  for (let i = 0; i < html.length; i++) {
    const ch = html[i]
    if (state.quote) {
      if (ch === state.quote) state.quote = null
    } else if (!state.inTag) {
      if (ch === '<') state.inTag = true
    } else if (ch === '"' || ch === "'") {
      state.quote = ch
    } else if (ch === '>') {
      state.inTag = false
    }
  }
  return state
}

// Are we inside an open tag at `nameStart`, given the state entering this chunk?
function inOpenTagAt(state, html, nameStart) {
  return advanceTagState({ inTag: state.inTag, quote: state.quote }, html.slice(0, nameStart)).inTag
}

// A valid binding opener sits at the very end of its HTML chunk, because the
// $(…) value token splits the chunk there. For openers in tag-attribute position:
//   - an `on*` name that is not a valid event handler is rejected outright;
//   - a non-empty remainder means the value is not a lone $(…) expression —
//     leading literal text (`onclick="run $(fn)"`) or raw inline JavaScript
//     (`onclick="alert(1)"`).
// Openers in text content are ignored (left as literal text). Fail loud rather
// than silently degrading a binding to a string attribute.
function assertNoInvalidBinding(html, state) {
  bindingOpenerPattern.lastIndex = 0
  let match
  while ((match = bindingOpenerPattern.exec(html))) {
    const [, leading, rawName, quote] = match
    const nameStart = match.index + leading.length
    if (!inOpenTagAt(state, html, nameStart)) continue

    const isEvent = rawName[0] !== '.'
    if (isEvent && !validEventName.test(rawName)) {
      throw new Error(`JST: ${rawName}="…" is not a valid JST event handler — an on<event> name must start with a letter (got event "${rawName.slice(2)}").`)
    }

    const remainder = html.slice(bindingOpenerPattern.lastIndex)
    if (remainder.length === 0) continue

    if (isEvent && remainder.includes(quote)) {
      throw new Error(`JST: ${rawName}="…" must be a single $(…) expression. Raw inline JavaScript in on* handlers is not allowed; wrap the handler in $(…).`)
    }
    throw new Error(`JST: ${rawName}="…" must contain exactly one $(…) expression and nothing else inside the quotes.`)
  }
}

function assertNoLegacyEventBinding(token, expressionToken, state) {
  const match = token.html.match(legacyEventTailPattern)
  if (!match || !(expressionToken instanceof JsExpressionToken)) return
  const nameStart = token.html.length - match[0].length + match[1].length
  if (!inOpenTagAt(state, token.html, nameStart)) return
  throw new Error(`JST: the @${match[2]}="…" event syntax was removed. Use on${match[2]}="…" instead.`)
}

function matchBinding(tokens, i, state) {
  const token = tokens[i]
  const expressionToken = tokens[i + 1]
  const closingToken = tokens[i + 2]

  if (!(token instanceof HtmlToken)) return null

  assertNoInvalidBinding(token.html, state)
  assertNoLegacyEventBinding(token, expressionToken, state)

  const match = token.html.match(bindingTailPattern)
  if (!match) return null

  const [fullMatch, leading, rawName, quote] = match
  const nameStart = token.html.length - fullMatch.length + leading.length
  if (!inOpenTagAt(state, token.html, nameStart)) return null

  const { kind, name } = classifyBindingName(rawName)

  if (!(expressionToken instanceof JsExpressionToken)
    || !(closingToken instanceof HtmlToken)
    || !closingToken.html.startsWith(quote)) {
    throw new Error(`JST: ${rawName}="…" must contain exactly one $(…) expression and nothing else inside the quotes.`)
  }

  return {
    kind,
    name,
    expression: expressionToken.expression,
    htmlPrefix: token.html.slice(0, token.html.length - fullMatch.length + leading.length),
    htmlSuffix: closingToken.html.slice(1),
  }
}

function interpretTemplateTokens(templateTokens) {
  const processedTokens = mergeJsTokens(templateTokens)
  const instructions = []
  // Running HTML tag/quote state, so binding detection knows tag-attribute
  // position across chunks. Interpolation tokens ($(expr)/$identifier) emit
  // escaped text (no structural < or >) and sit inside the current quote, so
  // they do not advance the state; only literal HTML/whitespace/`$` does.
  const tagState = { inTag: false, quote: null }

  for (let i = 0; i < processedTokens.length; i++) {
    const binding = matchBinding(processedTokens, i, tagState)

    if (binding) {
      instructions.push(`lines.push(${JSON.stringify(binding.htmlPrefix)});`)
      instructions.push(`lines.push(__bind(${JSON.stringify(binding.kind)}, ${JSON.stringify(binding.name)}, (${binding.expression})));`)
      // The binding contributes htmlPrefix + `name="<value>"`: advance through
      // the prefix, then the attribute's value quote opens and closes (the
      // closing quote was sliced off the suffix), leaving us still in the tag.
      advanceTagState(tagState, binding.htmlPrefix)
      tagState.quote = null
      processedTokens[i + 2] = new HtmlToken(binding.htmlSuffix)
      i += 1 // the expression token was consumed by the binding
      continue
    }

    const token = processedTokens[i]
    const instruction = interpretTemplateToken(token)
    if (instruction === undefined) throw new Error(`Unknown token at index ${i}: ${token.constructor.name}`)
    instructions.push(instruction)

    if (token instanceof HtmlToken) advanceTagState(tagState, token.html)
    else if (token instanceof WhitespaceToken) advanceTagState(tagState, token.whitespace)
    else if (token instanceof Escaped$Token) advanceTagState(tagState, '$')
  }

  return ['const lines = [];', ...instructions, 'return lines.join("");'].join('\n')
}

// Generated push statements end with ';' so a following user code line that
// starts with '(' or '[' cannot be swallowed by automatic semicolon insertion.
function interpretTemplateToken(token) {
  if (token instanceof HtmlToken) return `lines.push(${JSON.stringify(token.html)});`
  if (token instanceof JsCodeToken) return token.code
  if (token instanceof Escaped$Token) return `lines.push('$');`
  if (token instanceof JsExpressionToken) return `lines.push(__esc(${token.expression}));`
  if (token instanceof JsIdentifierToken) return `lines.push(__esc(${token.identifier}));`
  if (token instanceof WhitespaceToken) return `lines.push(${JSON.stringify(token.whitespace)});`
}
/* ===== compiler.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
function kebabToCamel(name) {
  return name.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase())
}

function camelToKebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

const jsIdentifierPattern = /^[$_\p{ID_Start}][$\u200c\u200d\p{ID_Continue}]*$/u
const reservedPropNames = new Set([
  'arguments',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'eval',
  'export',
  'extends',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'el',
  'trustedHTML',
  'slot',
  'url',
  'once',
  'onDisconnect',
  'emit',
  '__esc',
  '__bind',
])

function parsePropsAttribute(value) {
  if (!value || !value.trim()) return []

  return value
    .split(/[\s,]+/)
    .filter(Boolean)
    .map(prop => {
      if (!jsIdentifierPattern.test(prop)) {
        throw new Error(`Invalid JST prop "${prop}". Props must be valid JavaScript identifiers.`)
      }
      if (reservedPropNames.has(prop)) {
        throw new Error(`Invalid JST prop "${prop}". Props cannot use JavaScript keywords or JST helper names.`)
      }
      return prop
    })
}

class TemplateRenderingFunction {
  #functionParams
  #functionBody
  #paramMap

  constructor(functionParams, functionBody, paramMap) {
    this.#functionParams = functionParams
    this.#functionBody = functionBody
    this.#paramMap = paramMap
  }

  get functionParams() { return this.#functionParams; }
  get functionBody() { return this.#functionBody; }
  get paramMap() { return this.#paramMap; }
}

function getTemplateRenderingFunctionParams(templateElement) {
  // Props are declared in one case-preserving attribute value:
  //   <script type="jst" name="todo-item" props="item onToggle">
  // HTML lowercases attribute names, but not quoted attribute values, so this
  // keeps internal JS identifiers greppable and supports expected names like
  // `name` without conflicting with the template's own `name` attribute.
  const paramMap = {}
  const props = parsePropsAttribute(templateElement.getAttribute('props') || '')

  props.forEach(prop => {
    paramMap[camelToKebab(prop)] = prop
  })

  return {
    functionParams: Array.from(new Set(props)),
    paramMap,
  }
}

function compileTemplateRenderingFunction(templateElement) {
  const program = parseTemplateScript(templateElement.innerHTML)
  const { functionParams, paramMap } = getTemplateRenderingFunctionParams(templateElement)
  const functionBody = interpretTemplateTokens(program.tokens)

  return new TemplateRenderingFunction(functionParams, functionBody, paramMap)
}
/* ===== jst.js ===== */
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
/**
 * JST Framework Core
 *
 * Templates are declared as <script type="jst" name="tag-name" props="prop otherProp">
 * and registered as real custom elements. Data flows in through attributes
 * (JSON-parsed primitives) or properties (rich values: el.items = [...]).
 * Data flows out through bubbling CustomEvents (el.emit('name', detail)).
 *
 * Inside templates:
 *   $(expr)                 escaped interpolation
 *   $(trustedHTML(expr))    unescaped interpolation (opt-in trusted HTML)
 *   $(url(expr))            URL helper for href/src values
 *   $(slot())               project the component's original child nodes
 *   $(slot('name', 'fb'))   project nodes marked slot="name", with a fallback
 *   .prop="$(expr)"         assign expr as a JS property on the element
 *   onevent.mod="$(fn)"     addEventListener('event', fn) with optional modifiers
 *   jst-model="prop"        local form shorthand: read prop, update el[prop]
 *   once('key', setup)      run setup once per connection, after the DOM commits;
 *                           a returned function is registered as disconnect cleanup
 *   jst-key="$(id)"         preserve keyed node identity while morphing
 *
 * State lives in this module. The ES-module exports are the canonical API; a
 * reduced `window.JST` global mirrors them for non-module/streamed consumers.
 */
/**
 * The version of the loaded runtime. Sourced from package.json and kept in sync
 * by a drift test (runtime_tests.mjs) — a browser ES module can't read
 * package.json at runtime, so this constant is the single in-runtime source of
 * truth. Useful given the no-build "serve the file directly" model: a stale
 * v0.1 cache renders identically to v0.2, so `JST.version` is the one-liner that
 * tells you which runtime is actually live.
 */
const version = '0.2.3'

const templates = new Map()
const config = {
  dev: false,
  autoRegister: true,
  autoRegisterRoot: null,
  resolveTemplate: null,
}

let templatesInitialized = false
let templateObserver = null
let versionAnnounced = false
const pendingTemplateResolutions = new Map()

/** In dev, log the live runtime version once so a stale cache is obvious. */
function announceVersion() {
  if (versionAnnounced || !config.dev) return;
  if (typeof console === 'undefined' || typeof console.info !== 'function') return;
  versionAnnounced = true;
  console.info(`JST ${version}`);
}

/** Values wrapped in RawHtml bypass interpolation escaping. */
class RawHtml {
  constructor(html) { this.html = html }
}

function trustedHTML(value) {
  if (value instanceof RawHtml) return value
  return new RawHtml(value == null ? '' : String(value))
}

function url(value) {
  const string = value == null ? '' : String(value).trim()
  const scheme = string.match(/^([a-z][a-z0-9+.-]*):/i)
  if (scheme && !['http', 'https', 'mailto', 'tel', 'ftp'].includes(scheme[1].toLowerCase())) {
    console.warn(`JST: blocked unsafe URL scheme in "${string}".`)
    return '#'
  }
  return string
}

function configure(options = {}) {
  const shouldRewire = Object.prototype.hasOwnProperty.call(options, 'autoRegister')
    || Object.prototype.hasOwnProperty.call(options, 'autoRegisterRoot')
    || Object.prototype.hasOwnProperty.call(options, 'resolveTemplate');

  Object.assign(config, options);
  announceVersion();

  if (shouldRewire && templateObserver) {
    templateObserver.disconnect();
    templateObserver = null;
  }

  observeNewTemplates();

  // Auto-init runs at module eval, before an importing module can call
  // configure() — so any resolveTemplate set here was null during the initial
  // scanForMissingTemplates, and components already in the server-rendered HTML
  // were skipped (resolveTemplateForName bails when the resolver isn't a
  // function). Re-scan now that the resolver exists. This is idempotent:
  // resolveTemplateForName ignores names already defined/registered and
  // coalesces in-flight fetches, so re-scanning costs nothing for resolved ones.
  if (templatesInitialized && typeof config.resolveTemplate === 'function') {
    scanForMissingTemplates(document.documentElement);
  }

  return config
}

function isCustomElementName(name) {
  return typeof name === 'string' && name.includes('-');
}

function templateSource(templateElement) {
  return templateElement.dataset?.jstSource || templateElement.ownerDocument?.baseURI || '';
}

function insertTemplateHtml(html, source) {
  const container = document.createElement('div');
  container.hidden = true;
  container.setAttribute('data-jst-resolved-from', source);
  container.innerHTML = html;
  container.querySelectorAll('script[type="jst"]').forEach(script => {
    script.dataset.jstSource = source;
  });

  (document.body || document.head || document.documentElement).appendChild(container);
  container.querySelectorAll('script[type="jst"]').forEach(registerCustomElementFromTemplate);
  return container;
}

async function resolveTemplateForName(name) {
  const resolver = config.resolveTemplate;
  if (typeof resolver !== 'function') return null;
  if (!isCustomElementName(name) || customElements.get(name) || templates.has(name)) return null;
  if (pendingTemplateResolutions.has(name)) return pendingTemplateResolutions.get(name);

  const resolution = Promise.resolve()
    .then(() => resolver(name))
    .then(async url => {
      if (!url) return null;
      const response = await fetch(url);
      if (!response.ok) throw new Error(`HTTP ${response.status} while fetching ${url}`);
      const html = await response.text();
      return insertTemplateHtml(html, String(url));
    })
    .catch(error => {
      console.error(`JST: Failed to resolve template for <${name}>:`, error);
      return null;
    })
    .finally(() => {
      pendingTemplateResolutions.delete(name);
    });

  pendingTemplateResolutions.set(name, resolution);
  return resolution;
}

function scanForMissingTemplates(root) {
  if (!root || typeof root.querySelectorAll !== 'function') return;

  const visit = element => {
    if (element.nodeType !== Node.ELEMENT_NODE) return;
    const name = element.tagName.toLowerCase();
    if (isCustomElementName(name) && !customElements.get(name)) resolveTemplateForName(name);
  };

  visit(root);
  root.querySelectorAll('*').forEach(visit);
}

function escapeHtml(value) {
  if (value == null) return ''
  if (value instanceof RawHtml) return value.html
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function createSlotPlaceholder(name, fallback) {
  const nameAttribute = name ? ` name="${escapeHtml(name)}"` : ''
  const fallbackHtml = fallback == null ? '' : escapeHtml(fallback)
  return new RawHtml(`<jst-slot${nameAttribute} style="display: contents">${fallbackHtml}</jst-slot>`)
}

function canMorphDom(host) {
  return typeof document?.createElement === 'function' && !!host?.childNodes;
}

function isManagedCustomElement(node) {
  return node?.nodeType === Node.ELEMENT_NODE
    && typeof customElements?.get === 'function'
    && !!customElements.get(node.tagName.toLowerCase());
}

function isSlotElement(node) {
  return node?.nodeType === Node.ELEMENT_NODE && node.tagName === 'JST-SLOT';
}

function nodesAreCompatible(currentNode, nextNode) {
  if (!currentNode || !nextNode) return false;
  if (currentNode.nodeType !== nextNode.nodeType) return false;

  if (currentNode.nodeType === Node.ELEMENT_NODE) {
    return currentNode.tagName === nextNode.tagName;
  }

  return true;
}

function getNodeKey(node) {
  if (node?.nodeType !== Node.ELEMENT_NODE) return null;
  if (node.hasAttribute('data-jst-leaving')) return null;
  return node.getAttribute('jst-key');
}

function findKeyedChild(host, nextNode, startIndex) {
  const key = getNodeKey(nextNode);
  if (key == null) return null;

  for (let i = startIndex; i < host.childNodes.length; i++) {
    const candidate = host.childNodes[i];
    if (getNodeKey(candidate) === key && nodesAreCompatible(candidate, nextNode)) {
      return candidate;
    }
  }

  return null;
}

function transitionName(node) {
  return node?.nodeType === Node.ELEMENT_NODE ? node.getAttribute('jst-transition') : null;
}

function parseCssTimeList(value) {
  return String(value || '')
    .split(',')
    .map(part => part.trim())
    .filter(Boolean)
    .map(part => part.endsWith('ms') ? Number.parseFloat(part) : Number.parseFloat(part) * 1000)
    .filter(Number.isFinite);
}

function transitionTimeoutMs(element) {
  if (typeof getComputedStyle !== 'function') return 0;
  const style = getComputedStyle(element);
  const transitionDurations = parseCssTimeList(style.transitionDuration);
  const transitionDelays = parseCssTimeList(style.transitionDelay);
  const animationDurations = parseCssTimeList(style.animationDuration);
  const animationDelays = parseCssTimeList(style.animationDelay);
  const maxFor = (durations, delays) => durations.reduce((max, duration, index) => {
    const delay = delays[index] ?? delays[0] ?? 0;
    return Math.max(max, duration + delay);
  }, 0);

  return Math.max(
    maxFor(transitionDurations, transitionDelays),
    maxFor(animationDurations, animationDelays),
  );
}

function nextFrame(callback) {
  if (typeof requestAnimationFrame === 'function') {
    requestAnimationFrame(() => requestAnimationFrame(callback));
    return;
  }
  setTimeout(callback, 0);
}

function afterTransition(element, callback) {
  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    element.removeEventListener('transitionend', finish);
    element.removeEventListener('animationend', finish);
    callback();
  };
  const timeout = transitionTimeoutMs(element);

  element.addEventListener('transitionend', finish);
  element.addEventListener('animationend', finish);
  setTimeout(finish, timeout > 0 ? timeout + 50 : 0);
}

function removeTransitionClasses(element, name, phase) {
  element.classList.remove(
    `${name}-${phase}-from`,
    `${name}-${phase}-active`,
    `${name}-${phase}-to`,
  );
}

function runEnterTransition(node) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) return;

  node.classList.add(`${name}-enter-from`, `${name}-enter-active`);
  nextFrame(() => {
    node.classList.remove(`${name}-enter-from`);
    node.classList.add(`${name}-enter-to`);
    afterTransition(node, () => removeTransitionClasses(node, name, 'enter'));
  });
}

function runLeaveTransition(node, remove) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) {
    remove();
    return;
  }

  node.setAttribute('data-jst-leaving', '');
  node.removeAttribute('jst-key');
  node.classList.add(`${name}-leave-from`, `${name}-leave-active`);
  nextFrame(() => {
    node.classList.remove(`${name}-leave-from`);
    node.classList.add(`${name}-leave-to`);
    afterTransition(node, () => {
      removeTransitionClasses(node, name, 'leave');
      remove();
    });
  });
}

function runMoveTransition(node) {
  const name = transitionName(node);
  if (!name || node.nodeType !== Node.ELEMENT_NODE) return;

  node.classList.add(`${name}-move`);
  afterTransition(node, () => node.classList.remove(`${name}-move`));
}

function insertRenderedNode(host, nextNode, beforeNode = null) {
  const inserted = cloneRenderedNode(nextNode);
  host.insertBefore(inserted, beforeNode);
  runEnterTransition(inserted);
  return inserted;
}

function removeRenderedNode(host, node) {
  runLeaveTransition(node, () => {
    if (node.parentNode === host) host.removeChild(node);
  });
  return node.parentNode !== host;
}

function escapeCssIdentifier(value) {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(value);
  return String(value).replace(/["\\]/g, '\\$&');
}

function syncAttributes(currentElement, nextElement) {
  Array.from(currentElement.attributes).forEach(attr => {
    if (!nextElement.hasAttribute(attr.name)) currentElement.removeAttribute(attr.name);
  });

  Array.from(nextElement.attributes).forEach(attr => {
    if (currentElement.getAttribute(attr.name) !== attr.value) {
      currentElement.setAttribute(attr.name, attr.value);
    }
  });
}

const booleanPropertyAttributes = {
  readOnly: 'readonly',
}

function booleanPropertyValue(element, name) {
  const attrName = booleanPropertyAttributes[name] || name.toLowerCase();
  if (!element.hasAttribute(attrName)) return false;
  const value = element.getAttribute(attrName);
  return value !== 'false' && value !== '0';
}

function syncBooleanProperty(currentElement, nextElement, name) {
  if (!(name in currentElement)) return;
  const value = booleanPropertyValue(nextElement, name);
  if (currentElement[name] !== value) currentElement[name] = value;
}

function syncBooleanPropertyIfDeclared(currentElement, nextElement, name) {
  const attrName = booleanPropertyAttributes[name] || name.toLowerCase();
  if (!nextElement.hasAttribute(attrName)) return;
  syncBooleanProperty(currentElement, nextElement, name);
}

function setLiveValue(element, value) {
  if (element.value !== value) element.value = value;
}

function syncFormProperties(currentElement, nextElement) {
  if (currentElement.nodeType !== Node.ELEMENT_NODE) return;

  const tagName = currentElement.tagName;

  if (tagName === 'INPUT') {
    if (nextElement.hasAttribute('value')) setLiveValue(currentElement, nextElement.getAttribute('value'));
    syncBooleanPropertyIfDeclared(currentElement, nextElement, 'checked');
  } else if (tagName === 'TEXTAREA') {
    if (currentElement.defaultValue !== nextElement.defaultValue) setLiveValue(currentElement, nextElement.value);
  } else if (tagName === 'SELECT') {
    if (nextElement.hasAttribute('value')) setLiveValue(currentElement, nextElement.getAttribute('value'));
  } else if (tagName === 'OPTION') {
    syncBooleanPropertyIfDeclared(currentElement, nextElement, 'selected');
  }

  ['disabled', 'required', 'readOnly', 'multiple'].forEach(prop => {
    syncBooleanProperty(currentElement, nextElement, prop);
  });
}

function cloneRenderedNode(nextNode) {
  const clone = nextNode.cloneNode(true);

  const syncTree = (current, next) => {
    if (current.nodeType !== Node.ELEMENT_NODE || next.nodeType !== Node.ELEMENT_NODE) return;
    syncFormProperties(current, next);

    const currentChildren = Array.from(current.childNodes);
    const nextChildren = Array.from(next.childNodes);
    nextChildren.forEach((nextChild, index) => {
      if (currentChildren[index]) syncTree(currentChildren[index], nextChild);
    });
  };

  syncTree(clone, nextNode);
  return clone;
}

function morphNode(currentNode, nextNode) {
  if (!nodesAreCompatible(currentNode, nextNode)) {
    const replacement = cloneRenderedNode(nextNode);
    currentNode.replaceWith(replacement);
    runEnterTransition(replacement);
    return;
  }

  if (currentNode.nodeType === Node.TEXT_NODE || currentNode.nodeType === Node.COMMENT_NODE) {
    if (currentNode.nodeValue !== nextNode.nodeValue) currentNode.nodeValue = nextNode.nodeValue;
    return;
  }

  syncAttributes(currentNode, nextNode);
  syncFormProperties(currentNode, nextNode);
  // Managed elements render their own children; slot elements hold projected
  // author content. Neither should have its children morphed from the parent's
  // output. The early return is below syncAttributes on purpose: syncAttributes
  // carries this render's fresh `jst-bound`/`jst-bind-N` markers (and attribute
  // props) onto the existing managed child, so the parent's #applyBindings pass
  // re-applies its `.prop=`/event bindings to the child — flowing updated data
  // into a nested managed component's props on a parent re-render — without
  // touching the child's own DOM. Do not hoist this return above syncAttributes.
  if (isManagedCustomElement(currentNode) || isSlotElement(currentNode)) return;
  morphChildren(currentNode, nextNode);
}

function morphChildren(host, nextParent) {
  const nextNodes = Array.from(nextParent.childNodes);
  let index = 0;

  while (index < nextNodes.length || index < host.childNodes.length) {
    const currentNode = host.childNodes[index];
    const nextNode = nextNodes[index];

    if (!nextNode) {
      if (!removeRenderedNode(host, currentNode)) index++;
      continue;
    }

    if (!currentNode) {
      insertRenderedNode(host, nextNode);
      index++;
      continue;
    }

    const nextKey = getNodeKey(nextNode);
    if (nextKey != null && getNodeKey(currentNode) !== nextKey) {
      const keyedMatch = findKeyedChild(host, nextNode, index + 1);
      if (keyedMatch) {
        host.insertBefore(keyedMatch, currentNode);
        morphNode(keyedMatch, nextNode);
        runMoveTransition(keyedMatch);
      } else {
        insertRenderedNode(host, nextNode, currentNode);
      }
      index++;
      continue;
    }

    if (getNodeKey(currentNode) != null && nextKey == null && !nodesAreCompatible(currentNode, nextNode)) {
      insertRenderedNode(host, nextNode, currentNode);
      index++;
      continue;
    }

    if (!nodesAreCompatible(currentNode, nextNode)) {
      const replacement = cloneRenderedNode(nextNode);
      host.replaceChild(replacement, currentNode);
      runEnterTransition(replacement);
      index++;
      continue;
    }

    morphNode(currentNode, nextNode);
    index++;
  }
}

function applyRenderedHtml(host, html) {
  if (!canMorphDom(host)) {
    host.innerHTML = html;
    return;
  }

  const template = document.createElement('template');
  template.innerHTML = html;
  morphChildren(host, template.content);
}

const jsonLikePattern = /^(?:true|false|null|-?\d|\[|\{|")/

/**
 * Attributes arrive as strings. Values that look like JSON (numbers, booleans,
 * arrays, objects, quoted strings) are parsed so count="0" renders as a number.
 * Anything else stays a plain string. No eval involved.
 */
function parseAttributeValue(rawValue) {
  if (rawValue === null) return undefined
  const trimmed = rawValue.trim()
  if (!jsonLikePattern.test(trimmed)) return rawValue
  try { return JSON.parse(trimmed) } catch { return rawValue }
}

const bindingAttributePattern = /^jst-bind-(\d+)$/
const boundListeners = new WeakMap()
const modelListeners = new WeakMap()

const keyModifiers = {
  enter: 'Enter',
  escape: 'Escape',
  esc: 'Escape',
  tab: 'Tab',
  space: ' ',
  up: 'ArrowUp',
  down: 'ArrowDown',
  left: 'ArrowLeft',
  right: 'ArrowRight',
}

function parseEventDescriptor(descriptor) {
  const [eventName, ...modifiers] = descriptor.split('.');
  return { eventName, modifiers };
}

function valueFromModelControl(element, currentValue) {
  if (element instanceof HTMLInputElement && element.type === 'checkbox') {
    if (Array.isArray(currentValue)) {
      const next = currentValue.filter(value => String(value) !== element.value);
      if (element.checked) next.push(element.value);
      return next;
    }
    return element.checked;
  }

  if (element instanceof HTMLInputElement && element.type === 'radio') {
    return element.checked ? element.value : currentValue;
  }

  if (element instanceof HTMLSelectElement && element.multiple) {
    return Array.from(element.selectedOptions).map(option => option.value);
  }

  return element.value;
}

function syncModelControl(element, value) {
  if (element instanceof HTMLInputElement && element.type === 'checkbox') {
    const checked = Array.isArray(value)
      ? value.map(String).includes(element.value)
      : Boolean(value);
    if (element.checked !== checked) element.checked = checked;
    return;
  }

  if (element instanceof HTMLInputElement && element.type === 'radio') {
    const checked = value != null && String(value) === element.value;
    if (element.checked !== checked) element.checked = checked;
    return;
  }

  if (element instanceof HTMLSelectElement && element.multiple) {
    const selected = Array.isArray(value) ? value.map(String) : [];
    Array.from(element.options).forEach(option => {
      option.selected = selected.includes(option.value);
    });
    return;
  }

  if ('value' in element && element.value !== (value == null ? '' : String(value))) {
    element.value = value == null ? '' : String(value);
  }
}

function buildEventListener(element, descriptor, handler) {
  const { eventName, modifiers } = parseEventDescriptor(descriptor);
  const modifierSet = new Set(modifiers);
  const options = {
    capture: modifierSet.has('capture'),
    passive: modifierSet.has('passive'),
    once: modifierSet.has('once'),
  };
  const keyChecks = modifiers
    .filter(modifier => keyModifiers[modifier])
    .map(modifier => keyModifiers[modifier]);

  let listener = event => {
    if (keyChecks.length && !keyChecks.includes(event.key)) return;
    if (modifierSet.has('self') && event.target !== element) return;
    if (modifierSet.has('prevent')) event.preventDefault();
    if (modifierSet.has('stop')) event.stopPropagation();
    return handler(event);
  };

  const debounceIndex = modifiers.indexOf('debounce');
  if (debounceIndex !== -1) {
    const delay = Number(modifiers[debounceIndex + 1]) || 250;
    const original = listener;
    let timeout = null;
    listener = event => {
      clearTimeout(timeout);
      timeout = setTimeout(() => original(event), delay);
    };
  }

  return {
    eventName,
    target: modifierSet.has('outside') ? document : element,
    options,
    listener: modifierSet.has('outside')
      ? event => {
          if (!element.contains(event.target)) listener(event);
        }
      : listener,
  };
}

function applyBinding(element, { kind, name, value }) {
  if (kind === 'prop') {
    if (!Object.is(element[name], value)) element[name] = value
    return
  }

  const listeners = boundListeners.get(element) || {}
  if (listeners[name]) {
    listeners[name].target.removeEventListener(listeners[name].eventName, listeners[name].listener, listeners[name].options)
  }

  if (typeof value === 'function') {
    const binding = buildEventListener(element, name, value)
    binding.target.addEventListener(binding.eventName, binding.listener, binding.options)
    listeners[name] = binding
    boundListeners.set(element, listeners)
    return binding
  } else {
    delete listeners[name]
  }

  boundListeners.set(element, listeners)
  return null
}

function applyModelBinding(host, element, propName, paramNames) {
  const previous = modelListeners.get(element);
  if (previous) element.removeEventListener(previous.eventName, previous.listener);

  if (!paramNames.includes(propName)) {
    console.warn(`JST: jst-model="${propName}" does not match a declared prop on <${host.tagName.toLowerCase()}>.`);
  }

  syncModelControl(element, host._jstGetParam(propName));

  const eventName = element instanceof HTMLSelectElement
    || (element instanceof HTMLInputElement && (element.type === 'checkbox' || element.type === 'radio'))
    ? 'change'
    : 'input';
  const listener = () => {
    host[propName] = valueFromModelControl(element, host._jstGetParam(propName));
  };
  element.addEventListener(eventName, listener);
  element.removeAttribute('jst-model');
  modelListeners.set(element, { eventName, listener });
}

function registerCustomElementFromTemplate(templateElement) {
  const customElementName = templateElement.getAttribute('name')?.toLowerCase();
  const source = templateSource(templateElement);

  // Custom elements MUST have a hyphen in their name
  if (!customElementName || !customElementName.includes('-')) {
    console.error(`JST Error: "${customElementName}" is not a valid custom element name. It MUST contain a hyphen (e.g. jst-${customElementName}).`, source);
    return;
  }

  if (templateElement.__jstRegisteredName === customElementName) {
    return customElements.get(customElementName);
  }

  const renderFunction = compileTemplateRenderingFunction(templateElement);

  const elementClass = defineCustomElementFromRender({
    customElementName,
    paramNames: renderFunction.functionParams,
    attributeToParam: renderFunction.paramMap,
    renderFunctionBody: renderFunction.functionBody,
    source,
    createRenderFunction: () => new Function(
      ...renderFunction.functionParams,
      'el',
      'slot',
      'onDisconnect',
      '__esc',
      '__bind',
      'url',
      'once',
      'trustedHTML',
      renderFunction.functionBody,
    ),
  });

  if (elementClass) templateElement.__jstRegisteredName = customElementName;
  return elementClass;
}

function registerPrecompiledTemplate(customElementName, paramNames, attributeToParam, renderFunction, source = 'precompiled') {
  if (!customElementName || !customElementName.includes('-')) {
    console.error(`JST Error: "${customElementName}" is not a valid custom element name. It MUST contain a hyphen (e.g. jst-${customElementName}).`, source);
    return;
  }

  return defineCustomElementFromRender({
    customElementName: customElementName.toLowerCase(),
    paramNames,
    attributeToParam,
    renderFunctionBody: renderFunction.toString(),
    source,
    createRenderFunction: () => renderFunction,
  });
}

function defineCustomElementFromRender({
  customElementName,
  paramNames,
  attributeToParam,
  renderFunctionBody,
  source,
  createRenderFunction,
}) {
  if (templates.has(customElementName)) {
    console.warn(`JST: Duplicate template name "${customElementName}" ignored.`, source);
    return customElements.get(customElementName);
  }

  templates.set(customElementName, {
    functionParams: paramNames,
    paramMap: attributeToParam,
    source,
  });

  if (customElements.get(customElementName)) {
    console.warn(`JST: Custom element <${customElementName}> is already registered.`, source);
    return customElements.get(customElementName);
  }

  let compiledRender = null;

  const CustomElementClass = class extends HTMLElement {
    #params = {};
    #renderQueued = false;
    #slotContent = null;
    #slotContentDetached = false;
    #rendering = false;
    #slotObserver = null;
    #disconnectCleanups = new Set();
    #onceKeys = new Set();
    #connectionEpoch = 0;
    #outsideTracked = new WeakSet();

    static get observedAttributes() {
      return Object.keys(attributeToParam);
    }

    connectedCallback() {
      // Each connection is its own epoch; deferred once() setups captured under
      // a stale epoch (e.g. a synchronous disconnect+reconnect) are discarded.
      this.#connectionEpoch++;
      this.#captureSlotContent();
      this.#observeSlotMutations();
      this.#upgradeProperties();
      this.requestRender();
    }

    disconnectedCallback() {
      this.#slotObserver?.disconnect();
      this.#slotObserver = null;

      this.#disconnectCleanups.forEach(cleanup => {
        try {
          cleanup();
        } catch (error) {
          console.error(`JST disconnect cleanup error in <${customElementName}>:`, error);
        }
      });
      this.#disconnectCleanups.clear();
      this.#onceKeys.clear();
    }

    attributeChangedCallback(name, oldValue, newValue) {
      if (oldValue === newValue) return;
      this.#params[attributeToParam[name]] = parseAttributeValue(newValue);
      if (this.isConnected) this.requestRender();
    }

    /** Dispatch a bubbling CustomEvent. Data out: parents/pages listen for these. */
    emit(eventName, detail) {
      return this.dispatchEvent(new CustomEvent(eventName, { detail, bubbles: true, composed: true }));
    }

    requestRender() {
      if (this.#renderQueued) return;
      this.#renderQueued = true;

      queueMicrotask(() => {
        this.#renderQueued = false;
        if (this.isConnected) this.render();
      });
    }

    render() {
      if (!this.isConnected) return;

      const bindings = [];

      try {
        compiledRender = compiledRender || createRenderFunction();

        const html = compiledRender.call(
          this,
          ...paramNames.map(param => this.#params[param]),
          this,
          createSlotPlaceholder,
          cleanup => this.#registerDisconnectCleanup(cleanup),
          escapeHtml,
          (kind, name, value) => ` jst-bound jst-bind-${bindings.push({ kind, name, value }) - 1}=""`,
          url,
          (key, setupFn) => this.#runOnce(key, setupFn),
          trustedHTML,
        );

        this.#slotObserver?.disconnect();
        this.#slotObserver = null;
        this.#rendering = true;
        try {
          this.#detachSlotContent();
          applyRenderedHtml(this, html);
          this.#applyBindings(bindings);
          this.#applyModelBindings();
          this.#fillSlots();
        } finally {
          this.#rendering = false;
          this.#observeSlotMutations();
        }
      } catch (e) {
        console.error(`JST Render Error in <${customElementName}>:`, e);
        console.groupCollapsed('--- Problematic Generated Code ---');
        console.log(renderFunctionBody);
        console.groupEnd();
        if (config.dev) this.#showDevError(e);
      }
    }

    _jstGetParam(param) { return this.#params[param]; }

    _jstSetParam(param, value) {
      const previous = this.#params[param];
      this.#params[param] = value;
      const isMutableReference = value !== null && (typeof value === 'object' || typeof value === 'function');
      if (Object.is(previous, value) && !isMutableReference) return;
      this.requestRender();
    }

    #registerDisconnectCleanup(cleanup) {
      if (typeof cleanup !== 'function') return cleanup;
      this.#disconnectCleanups.add(cleanup);
      return cleanup;
    }

    #runOnce(key, setupFn) {
      if (this.#onceKeys.has(key)) return undefined;
      if (typeof setupFn !== 'function') return undefined;

      this.#onceKeys.add(key);

      // The template body runs before this render commits, so the component's
      // own rendered DOM and projected slots don't exist yet. Defer setup to a
      // microtask so it sees the committed DOM, and register whatever it returns
      // as disconnect cleanup, so callers never have to wire teardown by hand.
      const epoch = this.#connectionEpoch;
      queueMicrotask(() => {
        if (!this.isConnected || this.#connectionEpoch !== epoch || !this.#onceKeys.has(key)) return;
        try {
          const cleanup = setupFn();
          if (typeof cleanup === 'function') this.#registerDisconnectCleanup(cleanup);
        } catch (error) {
          this.#onceKeys.delete(key);
          console.error(`JST once("${key}") setup error in <${customElementName}>:`, error);
          if (config.dev) this.#showDevError(error);
        }
      });

      return undefined;
    }

    #showDevError(error) {
      this.innerHTML = `<pre class="jst-error" role="alert">JST Render Error in &lt;${escapeHtml(customElementName)}&gt;\n${escapeHtml(error?.stack || error?.message || error)}</pre>`;
    }

    /**
     * A property assigned before the element upgrades lands as an own property
     * that shadows the prototype accessor. Re-route it through the setter.
     */
    #upgradeProperties() {
      paramNames.forEach(param => {
        if (Object.prototype.hasOwnProperty.call(this, param)) {
          const value = this[param];
          delete this[param];
          this[param] = value;
        }
      });
    }

    /**
     * On first connect the element's children are the author's content.
     * Capture references so the template can project them via $(slot()).
     * The nodes stay in the document until the first render so they remain
     * reachable (getElementById, listeners) in the meantime.
     */
    #captureSlotContent() {
      if (this.#slotContent || !this.childNodes) return;

      const named = new Map();
      const defaultNodes = [];

      Array.from(this.childNodes).forEach(node => {
        const slotName = node.nodeType === Node.ELEMENT_NODE ? node.getAttribute('slot') : null;
        if (slotName) {
          if (!named.has(slotName)) named.set(slotName, []);
          named.get(slotName).push(node);
        } else {
          defaultNodes.push(node);
        }
      });

      this.#slotContent = { defaultNodes, named };
    }

    #observeSlotMutations() {
      if (this.#slotObserver || typeof MutationObserver === 'undefined') return;

      this.#slotObserver = new MutationObserver(mutations => {
        if (this.#rendering) return;

        mutations.forEach(mutation => {
          mutation.addedNodes.forEach(node => {
            if (node.nodeType !== Node.ELEMENT_NODE && node.nodeType !== Node.TEXT_NODE) return;
            if (!this.#slotContent) this.#captureSlotContent();

            const slotName = node.nodeType === Node.ELEMENT_NODE ? node.getAttribute('slot') : null;
            if (slotName) {
              if (!this.#slotContent.named.has(slotName)) this.#slotContent.named.set(slotName, []);
              const nodes = this.#slotContent.named.get(slotName);
              if (!nodes.includes(node)) nodes.push(node);
            } else if (!this.#slotContent.defaultNodes.includes(node)) {
              this.#slotContent.defaultNodes.push(node);
            }

            this.#rendering = true;
            try {
              this.#placeSlotContent(slotName);
            } finally {
              this.#rendering = false;
            }
          });
        });
      });

      this.#slotObserver.observe(this, { childList: true });
    }

    /**
     * Detach the captured author content right before the first morph, so the
     * morph never mutates author nodes and #fillSlots can re-project them.
     * Runs synchronously inside render(): no observable detached window.
     */
    #detachSlotContent() {
      if (this.#slotContentDetached || !this.#slotContent) return;
      this.#slotContentDetached = true;

      this.#slotContent.defaultNodes.forEach(node => node.remove?.());
      this.#slotContent.named.forEach(nodes => nodes.forEach(node => node.remove?.()));
    }

    #applyBindings(bindings) {
      if (!bindings.length || typeof this.querySelectorAll !== 'function') return;

      // Binding markers are stripped synchronously after every render, so any
      // marker present right now was emitted by this render's binding table —
      // including markers inside a nested component's light DOM.
      this.querySelectorAll('[jst-bound]').forEach(element => {
        Array.from(element.attributes).forEach(attribute => {
          const match = attribute.name.match(bindingAttributePattern);
          if (!match) return;

          element.removeAttribute(attribute.name);
          const binding = bindings[Number(match[1])];
          if (!binding) return;
          const applied = applyBinding(element, binding);
          // `.outside` listeners live on `document`, so they outlive the host
          // unless explicitly removed. Element-targeted listeners die with their
          // element; document-targeted ones leak and fire after disconnect.
          // Register one cleanup per element that strips its document listeners.
          if (applied && applied.target === document && !this.#outsideTracked.has(element)) {
            this.#outsideTracked.add(element);
            this.#registerDisconnectCleanup(() => {
              const current = boundListeners.get(element);
              if (!current) return;
              Object.values(current).forEach(b => {
                if (b.target === document) {
                  b.target.removeEventListener(b.eventName, b.listener, b.options);
                }
              });
            });
          }
        });

        element.removeAttribute('jst-bound');
      });
    }

    #applyModelBindings() {
      if (typeof this.querySelectorAll !== 'function') return;

      this.querySelectorAll('[jst-model]').forEach(element => {
        applyModelBinding(this, element, element.getAttribute('jst-model'), paramNames);
      });
    }

    #fillSlots() {
      if (typeof this.querySelectorAll !== 'function') return;

      this.querySelectorAll('jst-slot').forEach(slotElement => {
        if (slotElement.__jstFilled) return;
        slotElement.__jstFilled = true;

        this.#placeSlotContent(slotElement.getAttribute('name'));
      });
    }

    #placeSlotContent(name) {
      if (typeof this.querySelector !== 'function') return;
      const selector = name ? `jst-slot[name="${escapeCssIdentifier(name)}"]` : 'jst-slot:not([name])';
      const slotElement = this.querySelector(selector);
      if (!slotElement) return;

      const nodes = (name
        ? this.#slotContent?.named.get(name)
        : this.#slotContent?.defaultNodes) || [];

      if (nodes.length) slotElement.replaceChildren(...nodes);
    }
  };

  // Each declared prop becomes a real property: el.items = [...] re-renders.
  paramNames.forEach(param => {
    if (Object.prototype.hasOwnProperty.call(CustomElementClass.prototype, param)) {
      console.warn(`JST: Prop "${param}" on <${customElementName}> clashes with a component member and will not get a property accessor.`);
      return;
    }

    Object.defineProperty(CustomElementClass.prototype, param, {
      configurable: true,
      enumerable: true,
      get() { return this._jstGetParam(param); },
      set(value) { this._jstSetParam(param, value); },
    });
  });

  customElements.define(customElementName, CustomElementClass);
  if (config.dev) console.log(`JST: Registered <${customElementName}>`, source);
  return CustomElementClass;
}

function initializeTemplates() {
  if (templatesInitialized) return templates;
  templatesInitialized = true;
  announceVersion();

  document.querySelectorAll('script[type="jst"]').forEach(registerCustomElementFromTemplate);
  observeNewTemplates();
  scanForMissingTemplates(document.documentElement);

  return templates;
}

/**
 * Templates that arrive after initial load (e.g. inside an htmx/fetch fragment)
 * register automatically, so a server can ship component definitions on demand.
 */
function observeNewTemplates() {
  if (templateObserver || typeof MutationObserver === 'undefined') return;
  if (config.autoRegister === false
    && typeof config.resolveTemplate !== 'function') return;

  templateObserver = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      mutation.addedNodes.forEach(node => {
        if (node.nodeType !== Node.ELEMENT_NODE) return;
        if (config.autoRegister !== false) {
          if (node.matches?.('script[type="jst"]')) registerCustomElementFromTemplate(node);
          node.querySelectorAll?.('script[type="jst"]').forEach(registerCustomElementFromTemplate);
        }
        scanForMissingTemplates(node);
      });
    });
  });

  const root = config.autoRegisterRoot || document.documentElement;
  templateObserver.observe(root, { childList: true, subtree: true });
}

function resetJstForTests() {
  templates.clear();
}

/**
 * The ES-module exports are canonical. This publishes a reduced `window.JST`
 * global — the handful of entry points a non-module or server-streamed page
 * needs (configure, trustedHTML/url helpers, register/init) plus the live
 * `config` object — without re-exposing internal state like the template map.
 */
function publishJstApi() {
  if (typeof window === 'undefined') return;

  window.JST = {
    ...window.JST,
    version,
    configure,
    trustedHTML,
    url,
    registerCustomElementFromTemplate,
    registerPrecompiledTemplate,
    initializeTemplates,
    config,
  };
}

publishJstApi();
initializeTemplates();
})();
