#!/usr/bin/env node
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
/**
 * Build the classic/global runtime from the ES-module sources.
 *
 * The ES-module runtime (`jst.js` + 6 siblings) can't load over `file://` —
 * browsers block module imports from disk. This concatenates the modules into a
 * single classic `<script>`-able IIFE that exposes `window.JST` and self-inits,
 * so a copied example / local prototype / single generated HTML file runs with
 * no server and no build:
 *
 *   <script src="jst.global.js"></script>   <!-- works from file:// -->
 *
 * Outputs (written to the repo root):
 *   - jst.global.js       unminified bundle (committed; CDN-pinnable at a tag)
 *   - jst.global.min.js   minified via esbuild
 * It also regenerates the inlined runtime in concerns-standalone.html so the
 * single-file demo stays in sync.
 *
 * Handling imports: named imports (`import { X } from …`) are dropped because the
 * bundle shares one scope. The namespace import (`import * as Tokens from
 * './tokens.js'`) is dropped too, but its `Tokens.X` references need a real
 * object — so after the target module we emit `const Tokens = { …its exports… }`.
 * Forgetting this shim is exactly what left the hand-built standalone throwing
 * `ReferenceError: Tokens is not defined`; the build + sync test prevent a repeat.
 *
 * Usage:
 *   node tools/build_global.mjs           # build + write artifacts, regen standalone
 *   node tools/build_global.mjs --check   # verify on-disk artifacts are in sync (CI)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// Dependency order: each module may reference symbols declared above it.
const MODULE_ORDER = ['tokens', 'input_reader', 'lexer', 'parser', 'interpreter', 'compiler', 'jst'];

const STANDALONE = path.join(repoRoot, 'concerns-standalone.html');
const GLOBAL_JS = path.join(repoRoot, 'jst.global.js');
const GLOBAL_MIN_JS = path.join(repoRoot, 'jst.global.min.js');

function readModule(name) {
  return fs.readFileSync(path.join(repoRoot, `${name}.js`), 'utf8');
}

/** Names declared with `export function|class|const|let|var <name>`. */
function exportedNames(source) {
  const re = /^export\s+(?:async\s+)?(?:function\*?|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm;
  const names = [];
  let match;
  while ((match = re.exec(source))) names.push(match[1]);
  return names;
}

/** `import * as NS from './mod.js'` occurrences across a source. */
function namespaceImports(source) {
  const re = /import\s+\*\s+as\s+([A-Za-z_$][\w$]*)\s+from\s+['"]\.\/([\w-]+)\.js['"]/g;
  const found = [];
  let match;
  while ((match = re.exec(source))) found.push({ ns: match[1], module: match[2] });
  return found;
}

/** Strip import statements (single- or multi-line) and the `export` keyword. */
function stripModuleSyntax(source) {
  return source
    .replace(/^import\b[\s\S]*?from\s*['"][^'"]+['"]\s*;?[ \t]*\r?\n/gm, '')
    .replace(/^export\s+/gm, '');
}

function readVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
  return pkg.version;
}

/** Assemble the full classic IIFE bundle string. */
export function buildGlobalBundle() {
  const version = readVersion();

  // Which modules are namespace-imported, and under what name.
  const shimsByModule = new Map(); // module -> Set(ns)
  for (const name of MODULE_ORDER) {
    for (const { ns, module } of namespaceImports(readModule(name))) {
      if (!shimsByModule.has(module)) shimsByModule.set(module, new Set());
      shimsByModule.get(module).add(ns);
    }
  }

  const parts = [
    `/*! JST global build v${version} — generated by tools/build_global.mjs. Do not edit by hand. */`,
    `/*! © Brent Jacobs · https://github.com/br3nt/jst · MIT */`,
    '(() => {',
    `'use strict';`,
  ];

  for (const name of MODULE_ORDER) {
    parts.push(`/* ===== ${name}.js ===== */`);
    parts.push(stripModuleSyntax(readModule(name)).trim());

    const shimNames = shimsByModule.get(name);
    if (shimNames) {
      const exports = exportedNames(readModule(name));
      for (const ns of shimNames) {
        parts.push(`/* namespace shim for \`import * as ${ns} from './${name}.js'\` */`);
        parts.push(`const ${ns} = { ${exports.join(', ')} };`);
      }
    }
  }

  parts.push('})();');
  return parts.join('\n') + '\n';
}

/**
 * Inline a freshly built bundle into concerns-standalone.html's runtime <script>.
 * Matches both the original block (`<script>\n(() => {…`) and an already-built
 * one (`<script data-jst-runtime>` with the generated banner), so regeneration
 * round-trips to an identical file — which is what `--check` relies on.
 */
function renderStandalone(html, bundle) {
  const blockRe = /<script(?: data-jst-runtime)?>\n(?:\/\*![^\n]*\*\/\n){0,2}\(\(\) => \{[\s\S]*?\}\)\(\);\n<\/script>/;
  if (!blockRe.test(html)) {
    throw new Error('build_global: could not locate the runtime <script> block in concerns-standalone.html');
  }
  // Function replacement: the bundle is full of `$` (JST interpolation syntax),
  // and a string replacement would interpret `$&`/`$\``/`$'` and splice the
  // surrounding file in. A function return is inserted literally.
  return html.replace(blockRe, () => `<script data-jst-runtime>\n${bundle}</script>`);
}

async function minify(source) {
  let esbuild;
  try {
    esbuild = await import('esbuild');
  } catch {
    throw new Error('build_global: esbuild is required to minify. Run `npm install` (it is a devDependency).');
  }
  const result = await esbuild.transform(source, { minify: true, legalComments: 'inline' });
  return result.code;
}

async function main() {
  const check = process.argv.includes('--check');
  const bundle = buildGlobalBundle();
  const standaloneHtml = fs.readFileSync(STANDALONE, 'utf8');
  const nextStandalone = renderStandalone(standaloneHtml, bundle);

  if (check) {
    const problems = [];
    const onDisk = fs.existsSync(GLOBAL_JS) ? fs.readFileSync(GLOBAL_JS, 'utf8') : null;
    if (onDisk !== bundle) problems.push('jst.global.js is out of sync with the modules');
    if (standaloneHtml !== nextStandalone) problems.push('concerns-standalone.html inlined runtime is out of sync');

    if (problems.length) {
      for (const p of problems) console.error(`build_global --check: ${p}`);
      console.error('Run `npm run build` to regenerate.');
      process.exit(1);
    }
    console.log('build_global --check: jst.global.js and concerns-standalone.html are in sync.');
    return;
  }

  fs.writeFileSync(GLOBAL_JS, bundle);
  fs.writeFileSync(STANDALONE, nextStandalone);
  const min = await minify(bundle);
  fs.writeFileSync(GLOBAL_MIN_JS, min);

  const kb = n => `${(n / 1024).toFixed(1)}kb`;
  console.log(`build_global: wrote jst.global.js (${kb(bundle.length)}), jst.global.min.js (${kb(min.length)}); regenerated concerns-standalone.html`);
}

main().catch(error => {
  console.error(error.message);
  process.exit(1);
});
