#!/usr/bin/env node
/*!
 * JST — JavaScript Templates · no-build web components in plain HTML
 * © Brent Jacobs (https://github.com/br3nt) · https://github.com/br3nt/jst
 */
import fs from 'node:fs';
import path from 'node:path';
import { compileTemplateRenderingFunction } from '../compiler.js';

const attrPattern = /([A-Za-z_:][\w:.-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+)))?/g;
const scriptPattern = /<script\b([^>]*\btype\s*=\s*(['"])jst\2[^>]*)>([\s\S]*?)<\/script\s*>/gi;

function usage() {
  console.error('Usage: node tools/precompile.mjs <input.html...> --out <templates.js> [--runtime ./jst.runtime.js] [--global]');
  console.error('  --global  emit a classic script that reads window.JST.registerPrecompiledTemplate');
  console.error('            (for the classic runtime build jst.runtime.global.js), instead of an ES import.');
  process.exit(1);
}

function parseArgs(argv) {
  const inputs = [];
  let out = null;
  let runtime = './jst.js';
  let global = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') {
      out = argv[++i];
    } else if (arg === '--runtime') {
      runtime = argv[++i];
    } else if (arg === '--global') {
      global = true;
    } else if (arg.startsWith('--')) {
      usage();
    } else {
      inputs.push(arg);
    }
  }

  if (!inputs.length || !out) usage();
  return { inputs, out, runtime, global };
}

function parseAttributes(openTag) {
  const attributes = [];
  attrPattern.lastIndex = 0;

  let match;
  while ((match = attrPattern.exec(openTag))) {
    const name = match[1].toLowerCase();
    const value = match[2] ?? match[3] ?? match[4] ?? '';
    attributes.push({ name, value });
  }

  return attributes;
}

function templateElement({ attributes, innerHTML }) {
  return {
    attributes,
    innerHTML,
    getAttribute(name) {
      return attributes.find(attr => attr.name === name)?.value ?? null;
    },
  };
}

function findTemplates(filePath) {
  const html = fs.readFileSync(filePath, 'utf8');
  const templates = [];

  scriptPattern.lastIndex = 0;
  let match;
  while ((match = scriptPattern.exec(html))) {
    const [, openTag, , innerHTML] = match;
    const attributes = parseAttributes(openTag);
    const name = attributes.find(attr => attr.name === 'name')?.value;
    if (!name) throw new Error(`${filePath}: JST template is missing a name attribute`);

    const compiled = compileTemplateRenderingFunction(templateElement({ attributes, innerHTML }));
    templates.push({
      filePath,
      name: name.toLowerCase(),
      params: compiled.functionParams,
      paramMap: compiled.paramMap,
      body: compiled.functionBody,
    });
  }

  return templates;
}

function functionName(index, name) {
  return `render_${index}_${name.replace(/[^A-Za-z0-9_$]/g, '_')}`;
}

function runtimeImport(runtime) {
  if (/^(?:[./]|[A-Za-z]+:)/.test(runtime)) return runtime;
  return runtime;
}

const { inputs, out, runtime, global } = parseArgs(process.argv.slice(2));
const allTemplates = inputs.flatMap(input => findTemplates(path.resolve(input)));

if (!allTemplates.length) {
  throw new Error('No <script type="jst"> templates found.');
}

// Two output shapes:
//  - ES module (default): imports registerPrecompiledTemplate from the runtime,
//    loaded with <script type="module">. Pair with jst.js or jst.runtime.js.
//  - --global: a classic IIFE that reads window.JST.registerPrecompiledTemplate,
//    loaded with a plain <script>. Pair with jst.global.js or
//    jst.runtime.global.js (which publish window.JST before this runs).
const lines = global
  ? [
      '/* This file is generated by tools/precompile.mjs --global. */',
      '(() => {',
      '  const { registerPrecompiledTemplate } = window.JST;',
      '',
    ]
  : [
      '/* This file is generated by tools/precompile.mjs. */',
      `import { registerPrecompiledTemplate } from ${JSON.stringify(runtimeImport(runtime))};`,
      '',
    ];

allTemplates.forEach((template, index) => {
  const fn = functionName(index, template.name);
  const args = [
    ...template.params,
    'el',
    'slot',
    'onDisconnect',
    '__esc',
    '__bind',
    'url',
    'once',
    'trustedHTML',
  ];

  lines.push(`function ${fn}(${args.join(', ')}) {`);
  lines.push(template.body);
  lines.push('}');
  lines.push(`registerPrecompiledTemplate(${JSON.stringify(template.name)}, ${JSON.stringify(template.params)}, ${JSON.stringify(template.paramMap)}, ${fn}, ${JSON.stringify(template.filePath)});`);
  lines.push('');
});

if (global) lines.push('})();');

fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
fs.writeFileSync(out, `${lines.join('\n')}\n`);

console.log(`Wrote ${allTemplates.length} precompiled JST template${allTemplates.length === 1 ? '' : 's'} to ${out}`);
